// <auto-generated>
// 40_filebase/76.shared.tag/v1.tags.yml から生成されます。直接編集しないでください。
// </auto-generated>

#nullable enable

using System.Collections.ObjectModel;

namespace AstralRecordApi.Models;

/// <summary>共有タグID定数。</summary>
public static class MasterTagIds
{
    /// <summary>装備種別タグ。</summary>
    public static class Equipment
    {
        /// <summary>アミュレット。</summary>
        public const string AMULET = "AMULET";
        /// <summary>タリスマン。</summary>
        public const string TALISMAN = "TALISMAN";
        /// <summary>チャーム。</summary>
        public const string CHARM = "CHARM";
        /// <summary>コア。</summary>
        public const string CORE = "CORE";
        /// <summary>レリック。</summary>
        public const string RELIC = "RELIC";
        /// <summary>剣。</summary>
        public const string SWORD = "SWORD";
        /// <summary>杖。</summary>
        public const string STAFF = "STAFF";
        /// <summary>弓。</summary>
        public const string BOW = "BOW";
        /// <summary>ツルハシ。</summary>
        public const string PICKAXE = "PICKAXE";
        /// <summary>斧。</summary>
        public const string AXE = "AXE";
        /// <summary>クワ。</summary>
        public const string HOE = "HOE";
    }
    /// <summary>機能種別タグ。</summary>
    public static class Activity
    {
        /// <summary>アクティブ。</summary>
        public const string ACTIVE = "active";
        /// <summary>パッシブ。</summary>
        public const string PASSIVE = "passive";
        /// <summary>Mob用。</summary>
        public const string MOB = "mob";
        /// <summary>フィールド。</summary>
        public const string FIELD = "field";
        /// <summary>ステータス。</summary>
        public const string STATUS = "status";
        /// <summary>スキルツリー。</summary>
        public const string SKILLTREE = "skilltree";
    }
    /// <summary>戦闘ロールタグ。</summary>
    public static class CombatRole
    {
        /// <summary>近接。</summary>
        public const string MELEE = "melee";
        /// <summary>遠隔。</summary>
        public const string RANGED = "ranged";
        /// <summary>魔法。</summary>
        public const string MAGIC = "magic";
        /// <summary>タンク。</summary>
        public const string TANK = "tank";
        /// <summary>アタッカー。</summary>
        public const string DEALER = "dealer";
        /// <summary>バランス。</summary>
        public const string BALANCED = "balanced";
        /// <summary>防御。</summary>
        public const string DEFENSE = "defense";
        /// <summary>攻撃。</summary>
        public const string OFFENSE = "offense";
        /// <summary>前衛。</summary>
        public const string FRONT = "front";
        /// <summary>弓。</summary>
        public const string BOW = "bow";
        /// <summary>杖。</summary>
        public const string STAFF = "staff";
        /// <summary>剣。</summary>
        public const string SWORD = "sword";
    }
    /// <summary>属性タグ。</summary>
    public static class Element
    {
        /// <summary>炎。</summary>
        public const string FIRE = "fire";
        /// <summary>氷。</summary>
        public const string ICE = "ice";
        /// <summary>雷。</summary>
        public const string LIGHTNING = "lightning";
        /// <summary>毒。</summary>
        public const string POISON = "poison";
        /// <summary>光。</summary>
        public const string LIGHT = "light";
        /// <summary>闇。</summary>
        public const string DARK = "dark";
        /// <summary>炎上。</summary>
        public const string BURNING = "burning";
        /// <summary>凍結。</summary>
        public const string FROZEN = "frozen";
        /// <summary>冷却。</summary>
        public const string CHILLED = "chilled";
        /// <summary>感電。</summary>
        public const string SHOCKED = "shocked";
        /// <summary>毒状態。</summary>
        public const string POISONED = "poisoned";
        /// <summary>盲目。</summary>
        public const string BLINDNESS = "blindness";
        /// <summary>弱体。</summary>
        public const string WEAKNESS = "weakness";
        /// <summary>回復阻害。</summary>
        public const string HEALING_INHIBITION = "healing_inhibition";
        /// <summary>状態異常。</summary>
        public const string CONDITION = "condition";
        /// <summary>属性。</summary>
        public const string ELEMENT = "element";
    }
    /// <summary>進行区分タグ。</summary>
    public static class Progression
    {
        /// <summary>初期。</summary>
        public const string STARTER = "starter";
        /// <summary>初心者。</summary>
        public const string BEGINNER = "beginner";
        /// <summary>一次職。</summary>
        public const string TIER1 = "tier1";
        /// <summary>序盤。</summary>
        public const string EARLY = "early";
        /// <summary>入口。</summary>
        public const string ENTRY = "entry";
        /// <summary>帰還。</summary>
        public const string RETURN = "return";
    }
    /// <summary>スキルツリータグ。</summary>
    public static class Skilltree
    {
        /// <summary>ルート／根。</summary>
        public const string ROOT = "root";
        /// <summary>共通。</summary>
        public const string SHARED = "shared";
        /// <summary>中核。</summary>
        public const string CORE = "core";
        /// <summary>基本能力。</summary>
        public const string PRIMARY = "primary";
        /// <summary>リソース。</summary>
        public const string RESOURCE = "resource";
        /// <summary>筋力。</summary>
        public const string STRENGTH = "strength";
        /// <summary>敏捷。</summary>
        public const string AGILITY = "agility";
        /// <summary>知力。</summary>
        public const string INTELLIGENCE = "intelligence";
        /// <summary>器用。</summary>
        public const string DEXTERITY = "dexterity";
        /// <summary>運。</summary>
        public const string LUCK = "luck";
        /// <summary>体力。</summary>
        public const string HEALTH = "health";
        /// <summary>マナ。</summary>
        public const string MANA = "mana";
        /// <summary>エネルギー。</summary>
        public const string ENERGY = "energy";
        /// <summary>シールド。</summary>
        public const string SHIELD = "shield";
        /// <summary>耐久。</summary>
        public const string DURABILITY = "durability";
        /// <summary>命中。</summary>
        public const string ACCURACY = "accuracy";
    }
    /// <summary>生物・種族タグ。</summary>
    public static class Creature
    {
        /// <summary>ドラゴン。</summary>
        public const string DRAGON = "dragon";
        /// <summary>ボス。</summary>
        public const string BOSS = "boss";
        /// <summary>ゴーレム。</summary>
        public const string GOLEM = "golem";
        /// <summary>獣。</summary>
        public const string BEAST = "beast";
        /// <summary>精霊。</summary>
        public const string SPIRIT = "spirit";
        /// <summary>守護者。</summary>
        public const string GUARDIAN = "guardian";
        /// <summary>アンデッド。</summary>
        public const string UNDEAD = "undead";
        /// <summary>スケルトン。</summary>
        public const string SKELETON = "skeleton";
        /// <summary>人型。</summary>
        public const string HUMANOID = "humanoid";
        /// <summary>ヤギ。</summary>
        public const string GOAT = "goat";
        /// <summary>オオカミ。</summary>
        public const string WOLF = "wolf";
        /// <summary>NPC。</summary>
        public const string NPC = "npc";
    }
    /// <summary>地域・環境タグ。</summary>
    public static class Location
    {
        /// <summary>ミズガルズ。</summary>
        public const string MIDGARD = "midgard";
        /// <summary>森林。</summary>
        public const string FOREST = "forest";
        /// <summary>草原。</summary>
        public const string GRASSLAND = "grassland";
        /// <summary>山岳。</summary>
        public const string MOUNTAIN = "mountain";
        /// <summary>サバンナ。</summary>
        public const string SAVANNA = "savanna";
        /// <summary>アカシア。</summary>
        public const string ACACIA = "acacia";
    }
    /// <summary>NPC役割タグ。</summary>
    public static class NpcRole
    {
        /// <summary>クラス案内。</summary>
        public const string CLASS_GUIDE = "class_guide";
        /// <summary>通貨交換。</summary>
        public const string CURRENCY_EXCHANGE = "currency_exchange";
        /// <summary>防具店。</summary>
        public const string ARMOR_SHOP = "armor_shop";
        /// <summary>武器店。</summary>
        public const string WEAPON_SHOP = "weapon_shop";
        /// <summary>店舗。</summary>
        public const string SHOP = "shop";
        /// <summary>買取。</summary>
        public const string SELL = "sell";
        /// <summary>倉庫。</summary>
        public const string STORAGE = "storage";
        /// <summary>ログインボーナス。</summary>
        public const string LOGIN_BONUS = "login_bonus";
        /// <summary>クエスト発行。</summary>
        public const string QUEST_GIVER = "quest_giver";
    }
    /// <summary>製作分類タグ。</summary>
    public static class Crafting
    {
        /// <summary>武器。</summary>
        public const string WEAPON = "weapon";
        /// <summary>防具。</summary>
        public const string ARMOR = "armor";
        /// <summary>鍛冶。</summary>
        public const string BLACKSMITH = "blacksmith";
        /// <summary>錬金。</summary>
        public const string ALCHEMY = "alchemy";
        /// <summary>消耗品。</summary>
        public const string CONSUMABLE = "consumable";
    }
    /// <summary>モチーフタグ。</summary>
    public static class Theme
    {
        /// <summary>管理者。</summary>
        public const string ADMINISTRATOR = "administrator";
        /// <summary>冒険者。</summary>
        public const string ADVENTURER = "adventurer";
        /// <summary>コマンド限定。</summary>
        public const string COMMAND_ONLY = "command-only";
        /// <summary>アストラル。</summary>
        public const string ASTRAL = "astral";
        /// <summary>蒼。</summary>
        public const string AZURE = "azure";
        /// <summary>残り火。</summary>
        public const string EMBER = "ember";
        /// <summary>星光。</summary>
        public const string STARLIGHT = "starlight";
        /// <summary>風。</summary>
        public const string WIND = "wind";
        /// <summary>風待ち。</summary>
        public const string WINDWAIT = "windwait";
        /// <summary>黄昏。</summary>
        public const string TWILIGHT = "twilight";
        /// <summary>苔。</summary>
        public const string MOSS = "moss";
        /// <summary>鉄。</summary>
        public const string IRON = "iron";
        /// <summary>石。</summary>
        public const string STONE = "stone";
    }
}

/// <summary>共有タグ定義。</summary>
public sealed record MasterTagDefinition(
    string Id,
    string DisplayName,
    string Description,
    string Category,
    IReadOnlyList<string> AppliesTo);

/// <summary>共有タグカタログ。</summary>
public static class MasterTags
{
    private static readonly IReadOnlyDictionary<string, MasterTagDefinition> Definitions =
        new ReadOnlyDictionary<string, MasterTagDefinition>(
            new Dictionary<string, MasterTagDefinition>(StringComparer.Ordinal)
            {
                ["AMULET"] = new("AMULET", "アミュレット", "アミュレット用アクセサリ枠へ装着できる装備。", "EQUIPMENT", ["EQUIPMENT"]),
                ["TALISMAN"] = new("TALISMAN", "タリスマン", "タリスマン用アクセサリ枠へ装着できる装備。", "EQUIPMENT", ["EQUIPMENT"]),
                ["CHARM"] = new("CHARM", "チャーム", "チャーム用アクセサリ枠へ装着できる装備。", "EQUIPMENT", ["EQUIPMENT"]),
                ["CORE"] = new("CORE", "コア", "コア用アクセサリ枠へ装着できる装備。", "EQUIPMENT", ["EQUIPMENT"]),
                ["RELIC"] = new("RELIC", "レリック", "レリック用アクセサリ枠へ装着できる装備。", "EQUIPMENT", ["EQUIPMENT"]),
                ["SWORD"] = new("SWORD", "剣", "剣として扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["STAFF"] = new("STAFF", "杖", "杖として扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["BOW"] = new("BOW", "弓", "弓として扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["PICKAXE"] = new("PICKAXE", "ツルハシ", "採掘用のツルハシとして扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["AXE"] = new("AXE", "斧", "伐採用の斧として扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["HOE"] = new("HOE", "クワ", "採取用のクワとして扱う装備。", "EQUIPMENT", ["EQUIPMENT", "GATHERING_REQUIRED_TOOL"]),
                ["active"] = new("active", "アクティブ", "能動的に発動するスキル。", "ACTIVITY", ["SKILL"]),
                ["passive"] = new("passive", "パッシブ", "常時または条件付きで自動適用されるスキル。", "ACTIVITY", ["SKILL"]),
                ["mob"] = new("mob", "Mob用", "Mob が使用するスキル。", "ACTIVITY", ["SKILL"]),
                ["field"] = new("field", "フィールド", "フィールド上の行動・効果に関係する分類。", "ACTIVITY", ["SKILL"]),
                ["status"] = new("status", "ステータス", "ステータス効果を持つスキルツリーノード。", "ACTIVITY", ["SKILLTREE_NODE"]),
                ["skilltree"] = new("skilltree", "スキルツリー", "スキルツリー機能への導線を持つ NPC。", "ACTIVITY", ["MOB"]),
                ["melee"] = new("melee", "近接", "近接戦闘を主とする分類。", "COMBAT_ROLE", ["CLASS", "SKILL", "MOB"]),
                ["ranged"] = new("ranged", "遠隔", "遠隔攻撃を主とする分類。", "COMBAT_ROLE", ["CLASS", "SKILL", "MOB"]),
                ["magic"] = new("magic", "魔法", "魔法攻撃または魔法系統の分類。", "COMBAT_ROLE", ["CLASS", "SKILL", "MOB"]),
                ["tank"] = new("tank", "タンク", "防御と敵対維持を主とするクラスロール。", "COMBAT_ROLE", ["CLASS"]),
                ["dealer"] = new("dealer", "アタッカー", "ダメージ出力を主とするクラスロール。", "COMBAT_ROLE", ["CLASS"]),
                ["balanced"] = new("balanced", "バランス", "複数の役割を均等に扱うクラス。", "COMBAT_ROLE", ["CLASS"]),
                ["defense"] = new("defense", "防御", "防御能力や耐久力に関係する分類。", "COMBAT_ROLE", ["SKILL", "SKILLTREE_NODE"]),
                ["offense"] = new("offense", "攻撃", "攻撃能力に関係する分類。", "COMBAT_ROLE", ["SKILLTREE_NODE"]),
                ["front"] = new("front", "前衛", "前線で戦うクラスロール。", "COMBAT_ROLE", ["CLASS"]),
                ["bow"] = new("bow", "弓", "弓系統に関係する分類。", "COMBAT_ROLE", ["CLASS", "SKILL"]),
                ["staff"] = new("staff", "杖", "杖系統に関係する分類。", "COMBAT_ROLE", ["CLASS"]),
                ["sword"] = new("sword", "剣", "剣系統に関係する分類。", "COMBAT_ROLE", ["CLASS"]),
                ["fire"] = new("fire", "炎", "炎属性または炎をモチーフとする分類。", "ELEMENT", ["SKILL", "SKILLTREE_NODE", "MOB"]),
                ["ice"] = new("ice", "氷", "氷属性に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["lightning"] = new("lightning", "雷", "雷属性に関係する分類。", "ELEMENT", ["SKILL", "SKILLTREE_NODE", "MOB"]),
                ["poison"] = new("poison", "毒", "毒属性に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["light"] = new("light", "光", "光属性に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["dark"] = new("dark", "闇", "闇属性に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["burning"] = new("burning", "炎上", "炎上状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["frozen"] = new("frozen", "凍結", "凍結状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["chilled"] = new("chilled", "冷却", "冷却状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["shocked"] = new("shocked", "感電", "感電状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["poisoned"] = new("poisoned", "毒状態", "毒状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["blindness"] = new("blindness", "盲目", "盲目状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["weakness"] = new("weakness", "弱体", "弱体状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["healing_inhibition"] = new("healing_inhibition", "回復阻害", "回復阻害状態に関係する分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["condition"] = new("condition", "状態異常", "状態異常系ノードをまとめる分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["element"] = new("element", "属性", "属性系ノードをまとめる分類。", "ELEMENT", ["SKILLTREE_NODE"]),
                ["starter"] = new("starter", "初期", "ゲーム開始時の初期クラス。", "PROGRESSION", ["CLASS"]),
                ["beginner"] = new("beginner", "初心者", "初心者向けのクラス。", "PROGRESSION", ["CLASS"]),
                ["tier1"] = new("tier1", "一次職", "一次職段階のクラス。", "PROGRESSION", ["CLASS"]),
                ["early"] = new("early", "序盤", "序盤に位置するスキルツリーノード。", "PROGRESSION", ["SKILLTREE_NODE"]),
                ["entry"] = new("entry", "入口", "コンテンツ入口への案内を行う NPC。", "PROGRESSION", ["MOB"]),
                ["return"] = new("return", "帰還", "コンテンツからの帰還を案内する NPC。", "PROGRESSION", ["MOB"]),
                ["root"] = new("root", "ルート／根", "スキルツリーの開始点、または根をモチーフとする分類。", "SKILLTREE", ["SKILLTREE_NODE", "MOB"]),
                ["shared"] = new("shared", "共通", "複数クラスで共有するスキルツリーノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["core"] = new("core", "中核", "スキルツリーの中核となるノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["primary"] = new("primary", "基本能力", "基本能力値に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["resource"] = new("resource", "リソース", "HP、MPなどのリソースに関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["strength"] = new("strength", "筋力", "筋力に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["agility"] = new("agility", "敏捷", "敏捷に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["intelligence"] = new("intelligence", "知力", "知力に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["dexterity"] = new("dexterity", "器用", "器用に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["luck"] = new("luck", "運", "運に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["health"] = new("health", "体力", "HPに関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["mana"] = new("mana", "マナ", "MPに関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["energy"] = new("energy", "エネルギー", "エネルギーに関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["shield"] = new("shield", "シールド", "シールド能力または盾を持つ Mob に関係する分類。", "SKILLTREE", ["SKILLTREE_NODE", "MOB"]),
                ["durability"] = new("durability", "耐久", "耐久力に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["accuracy"] = new("accuracy", "命中", "命中能力に関係するノード。", "SKILLTREE", ["SKILLTREE_NODE"]),
                ["dragon"] = new("dragon", "ドラゴン", "ドラゴン種の Mob。", "CREATURE", ["MOB"]),
                ["boss"] = new("boss", "ボス", "ボスとして扱う Mob。", "CREATURE", ["MOB"]),
                ["golem"] = new("golem", "ゴーレム", "ゴーレム種の Mob。", "CREATURE", ["MOB"]),
                ["beast"] = new("beast", "獣", "獣種の Mob。", "CREATURE", ["MOB"]),
                ["spirit"] = new("spirit", "精霊", "精霊種の Mob。", "CREATURE", ["MOB"]),
                ["guardian"] = new("guardian", "守護者", "守護者として配置される Mob。", "CREATURE", ["MOB"]),
                ["undead"] = new("undead", "アンデッド", "アンデッド種の Mob。", "CREATURE", ["MOB"]),
                ["skeleton"] = new("skeleton", "スケルトン", "スケルトン種の Mob。", "CREATURE", ["MOB"]),
                ["humanoid"] = new("humanoid", "人型", "人型の Mob。", "CREATURE", ["MOB"]),
                ["goat"] = new("goat", "ヤギ", "ヤギ種の Mob。", "CREATURE", ["MOB"]),
                ["wolf"] = new("wolf", "オオカミ", "オオカミ種の Mob。", "CREATURE", ["MOB"]),
                ["npc"] = new("npc", "NPC", "NPCとして扱う Mob。", "CREATURE", ["MOB"]),
                ["midgard"] = new("midgard", "ミズガルズ", "ミズガルズ地域に属する分類。", "LOCATION", ["MOB", "RECIPE"]),
                ["forest"] = new("forest", "森林", "森林地域に属する分類。", "LOCATION", ["MOB"]),
                ["grassland"] = new("grassland", "草原", "草原地域に属する分類。", "LOCATION", ["MOB"]),
                ["mountain"] = new("mountain", "山岳", "山岳地域に属する分類。", "LOCATION", ["SKILL", "MOB"]),
                ["savanna"] = new("savanna", "サバンナ", "サバンナ地域に属する分類。", "LOCATION", ["SKILL", "MOB"]),
                ["acacia"] = new("acacia", "アカシア", "アカシアをモチーフとする分類。", "LOCATION", ["MOB"]),
                ["class_guide"] = new("class_guide", "クラス案内", "クラス選択を案内する NPC。", "NPC_ROLE", ["MOB"]),
                ["currency_exchange"] = new("currency_exchange", "通貨交換", "通貨交換を提供する NPC。", "NPC_ROLE", ["MOB"]),
                ["armor_shop"] = new("armor_shop", "防具店", "防具を扱う店舗 NPC。", "NPC_ROLE", ["MOB"]),
                ["weapon_shop"] = new("weapon_shop", "武器店", "武器を扱う店舗 NPC。", "NPC_ROLE", ["MOB"]),
                ["shop"] = new("shop", "店舗", "店舗機能を持つ NPC。", "NPC_ROLE", ["MOB"]),
                ["sell"] = new("sell", "買取", "アイテム買取を提供する NPC。", "NPC_ROLE", ["MOB"]),
                ["storage"] = new("storage", "倉庫", "倉庫機能を提供する NPC。", "NPC_ROLE", ["MOB"]),
                ["login_bonus"] = new("login_bonus", "ログインボーナス", "ログインボーナスを提供する NPC。", "NPC_ROLE", ["MOB"]),
                ["quest_giver"] = new("quest_giver", "クエスト発行", "クエストを発行する NPC。", "NPC_ROLE", ["MOB"]),
                ["weapon"] = new("weapon", "武器", "武器を成果物とするレシピ。", "CRAFTING", ["RECIPE"]),
                ["armor"] = new("armor", "防具", "防具を成果物とするレシピ。", "CRAFTING", ["RECIPE"]),
                ["blacksmith"] = new("blacksmith", "鍛冶", "鍛冶設備や鍛冶工程で扱うレシピ。", "CRAFTING", ["RECIPE"]),
                ["alchemy"] = new("alchemy", "錬金", "錬金・調合工程で扱うレシピ。", "CRAFTING", ["RECIPE"]),
                ["consumable"] = new("consumable", "消耗品", "消耗品を成果物とするレシピ。", "CRAFTING", ["RECIPE"]),
                ["administrator"] = new("administrator", "管理者", "管理者専用クラス。", "THEME", ["CLASS"]),
                ["adventurer"] = new("adventurer", "冒険者", "冒険者クラスと関連スキル。", "THEME", ["CLASS", "SKILL"]),
                ["command-only"] = new("command-only", "コマンド限定", "コマンドからのみ利用する分類。", "THEME", ["CLASS"]),
                ["astral"] = new("astral", "アストラル", "星界をモチーフとする分類。", "THEME", ["SKILLTREE_NODE"]),
                ["azure"] = new("azure", "蒼", "蒼色をモチーフとする分類。", "THEME", ["SKILLTREE_NODE"]),
                ["ember"] = new("ember", "残り火", "残り火をモチーフとする分類。", "THEME", ["SKILLTREE_NODE"]),
                ["starlight"] = new("starlight", "星光", "星の光をモチーフとする分類。", "THEME", ["SKILLTREE_NODE"]),
                ["wind"] = new("wind", "風", "風をモチーフとする分類。", "THEME", ["SKILLTREE_NODE"]),
                ["windwait"] = new("windwait", "風待ち", "風待ちをモチーフとするスキルまたはMobの分類。", "THEME", ["SKILL", "MOB"]),
                ["twilight"] = new("twilight", "黄昏", "黄昏をモチーフとする分類。", "THEME", ["MOB"]),
                ["moss"] = new("moss", "苔", "苔をモチーフとする分類。", "THEME", ["MOB"]),
                ["iron"] = new("iron", "鉄", "鉄をモチーフとする分類。", "THEME", ["MOB"]),
                ["stone"] = new("stone", "石", "石をモチーフとする分類。", "THEME", ["SKILLTREE_NODE", "MOB"]),
            });

    /// <summary>IDをキーとする全タグ定義。</summary>
    public static IReadOnlyDictionary<string, MasterTagDefinition> All => Definitions;

    /// <summary>不変IDに対応するタグ定義を取得します。</summary>
    public static bool TryGet(string id, out MasterTagDefinition? definition) =>
        Definitions.TryGetValue(id, out definition);
}
