/* Existing HistoryDB migration. Apply once before deploying the Player Activity API. */
IF OBJECT_ID(N'dbo.player_activity_batch', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.player_activity_batch (batch_id UNIQUEIDENTIFIER NOT NULL, received_at DATETIME2(3) NOT NULL, CONSTRAINT PK_player_activity_batch PRIMARY KEY CLUSTERED (batch_id));
    CREATE TABLE dbo.player_ip_observation (event_id UNIQUEIDENTIFIER NOT NULL, observed_at DATETIME2(3) NOT NULL, global_ip NVARCHAR(45) NOT NULL, user_uuid UNIQUEIDENTIFIER NOT NULL, account_id UNIQUEIDENTIFIER NOT NULL, mcid NVARCHAR(20) NOT NULL, account_name NVARCHAR(50) NOT NULL, CONSTRAINT PK_player_ip_observation PRIMARY KEY CLUSTERED (event_id));
    CREATE INDEX IX_player_ip_observation_ip_observed ON dbo.player_ip_observation(global_ip, observed_at DESC);
    CREATE TABLE dbo.player_trade_activity (event_id UNIQUEIDENTIFIER NOT NULL, completed_at DATETIME2(3) NOT NULL, source_user_uuid UNIQUEIDENTIFIER NOT NULL, source_account_id UNIQUEIDENTIFIER NOT NULL, source_mcid NVARCHAR(20) NOT NULL, source_account_name NVARCHAR(50) NOT NULL, destination_user_uuid UNIQUEIDENTIFIER NOT NULL, destination_account_id UNIQUEIDENTIFIER NOT NULL, destination_mcid NVARCHAR(20) NOT NULL, destination_account_name NVARCHAR(50) NOT NULL, gold BIGINT NOT NULL, CONSTRAINT PK_player_trade_activity PRIMARY KEY CLUSTERED (event_id), CONSTRAINT CK_player_trade_activity_gold CHECK (gold >= 0));
    CREATE INDEX IX_player_trade_activity_completed_accounts ON dbo.player_trade_activity(completed_at DESC, source_account_id, destination_account_id);
    CREATE TABLE dbo.player_trade_activity_item (event_id UNIQUEIDENTIFIER NOT NULL, line_number INT NOT NULL, item_id NVARCHAR(100) NOT NULL, item_name NVARCHAR(200) NOT NULL, quantity BIGINT NOT NULL, CONSTRAINT PK_player_trade_activity_item PRIMARY KEY CLUSTERED(event_id,line_number), CONSTRAINT FK_player_trade_activity_item_event FOREIGN KEY(event_id) REFERENCES dbo.player_trade_activity(event_id) ON DELETE CASCADE, CONSTRAINT CK_player_trade_activity_item_quantity CHECK(quantity>=1));
    CREATE TABLE dbo.dungeon_clear_activity (event_id UNIQUEIDENTIFIER NOT NULL, dungeon_id NVARCHAR(100) NOT NULL, dungeon_name NVARCHAR(200) NOT NULL, started_at DATETIME2(3) NOT NULL, cleared_at DATETIME2(3) NOT NULL, CONSTRAINT PK_dungeon_clear_activity PRIMARY KEY CLUSTERED(event_id), CONSTRAINT CK_dungeon_clear_activity_time CHECK(cleared_at>=started_at));
    CREATE INDEX IX_dungeon_clear_activity_cleared_dungeon ON dbo.dungeon_clear_activity(cleared_at DESC,dungeon_id);
    CREATE TABLE dbo.dungeon_clear_participant (event_id UNIQUEIDENTIFIER NOT NULL, account_id UNIQUEIDENTIFIER NOT NULL, user_uuid UNIQUEIDENTIFIER NOT NULL, mcid NVARCHAR(20) NOT NULL, account_name NVARCHAR(50) NOT NULL, distance_meters DECIMAL(18,3) NULL, movement_sample_count INT NOT NULL, CONSTRAINT PK_dungeon_clear_participant PRIMARY KEY CLUSTERED(event_id,account_id), CONSTRAINT FK_dungeon_clear_participant_event FOREIGN KEY(event_id) REFERENCES dbo.dungeon_clear_activity(event_id) ON DELETE CASCADE, CONSTRAINT CK_dungeon_clear_participant_distance CHECK(distance_meters IS NULL OR distance_meters>=0), CONSTRAINT CK_dungeon_clear_participant_samples CHECK(movement_sample_count>=0));
    CREATE INDEX IX_dungeon_clear_participant_account_event ON dbo.dungeon_clear_participant(account_id,event_id);
    CREATE TABLE dbo.mob_damage_summary (event_id UNIQUEIDENTIFIER NOT NULL, mob_id NVARCHAR(100) NOT NULL, mob_name NVARCHAR(200) NOT NULL, window_started_at DATETIME2(3) NOT NULL, window_ended_at DATETIME2(3) NOT NULL, victim_user_uuid UNIQUEIDENTIFIER NOT NULL, victim_account_id UNIQUEIDENTIFIER NOT NULL, victim_mcid NVARCHAR(20) NOT NULL, victim_account_name NVARCHAR(50) NOT NULL, damage DECIMAL(18,3) NOT NULL, hit_count INT NOT NULL, CONSTRAINT PK_mob_damage_summary PRIMARY KEY CLUSTERED(event_id), CONSTRAINT CK_mob_damage_summary_time CHECK(window_ended_at>=window_started_at), CONSTRAINT CK_mob_damage_summary_damage CHECK(damage>=0), CONSTRAINT CK_mob_damage_summary_hits CHECK(hit_count>=0));
    CREATE INDEX IX_mob_damage_summary_mob_window ON dbo.mob_damage_summary(mob_id,window_ended_at DESC);
    CREATE TABLE dbo.mob_player_death (event_id UNIQUEIDENTIFIER NOT NULL, occurred_at DATETIME2(3) NOT NULL, mob_id NVARCHAR(100) NOT NULL, mob_name NVARCHAR(200) NOT NULL, victim_user_uuid UNIQUEIDENTIFIER NOT NULL, victim_account_id UNIQUEIDENTIFIER NOT NULL, victim_mcid NVARCHAR(20) NOT NULL, victim_account_name NVARCHAR(50) NOT NULL, CONSTRAINT PK_mob_player_death PRIMARY KEY CLUSTERED(event_id));
    CREATE INDEX IX_mob_player_death_mob_occurred ON dbo.mob_player_death(mob_id,occurred_at DESC);
END;
GO
