package io.github.maaasu.astralrecordgeyser;

import java.util.List;

/** RPGのGuiItemsに定義した固定ヘッドと同じtextures値を保持する。追加・変更時は両方を同期する。 */
final class BuiltinHeadTextures {
    static final String CURRENCY_HEAD_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmY5NmZmYjk5NzhlNTM2NGQxODkzMjA0ZWY0NzkxNjJjZjU2ZTE5NWRhN2NhYzE0MTBlYmEwNjkzMDUzOTViOCJ9fX0=";
    static final String OAK_WOOD_ARROW_UP_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA0MGZlODM2YTZjMmZiZDJjN2E5YzhlYzZiZTUxNzRmZGRmMWFjMjBmNTVlMzY2MTU2ZmE1ZjcxMmUxMCJ9fX0=";
    static final String OAK_WOOD_ARROW_DOWN_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQzNzM0NmQ4YmRhNzhkNTI1ZDE5ZjU0MGE5NWU0ZTc5ZGFlZGE3OTVjYmM1YTEzMjU2MjM2MzEyY2YifX19";
    static final String OAK_WOOD_ARROW_RIGHT_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19";
    static final String OAK_WOOD_ARROW_LEFT_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ==";
    static final String OAK_WOOD_BLANK_TEXTURE =
        "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWRiNTMyYjVjY2VkNDZiNGI1MzVlY2UxNmVjZWQ3YmJjNWNhYzU1NTk0ZDYxZThiOGY4ZWFjNDI5OWM5ZmMifX19";
    static final List<String> ALL = List.of(CURRENCY_HEAD_TEXTURE, OAK_WOOD_ARROW_UP_TEXTURE,
        OAK_WOOD_ARROW_DOWN_TEXTURE, OAK_WOOD_ARROW_RIGHT_TEXTURE, OAK_WOOD_ARROW_LEFT_TEXTURE,
        OAK_WOOD_BLANK_TEXTURE);

    private BuiltinHeadTextures() { }
}
