// <auto-generated>
// 40_filebase/76.shared.tag/v1.tags.yml から生成されます。直接編集しないでください。
// </auto-generated>

package io.github.maaasu.astralRecord.shared.masterdata.tag;

import java.util.List;
import java.util.Map;

/** 共有タグカタログから生成されたタグID定数です。 */
public final class MasterTagIds {
    private MasterTagIds() {
    }

    /** 装備種別タグです。 */
    public static final class Equipment {
        private Equipment() {
        }

        /** アミュレット: アミュレット用アクセサリ枠へ装着できる装備。 */
        public static final String AMULET = "AMULET";

        /** タリスマン: タリスマン用アクセサリ枠へ装着できる装備。 */
        public static final String TALISMAN = "TALISMAN";

        /** チャーム: チャーム用アクセサリ枠へ装着できる装備。 */
        public static final String CHARM = "CHARM";

        /** コア: コア用アクセサリ枠へ装着できる装備。 */
        public static final String CORE = "CORE";

        /** レリック: レリック用アクセサリ枠へ装着できる装備。 */
        public static final String RELIC = "RELIC";

        /** 剣: 剣として扱う装備。 */
        public static final String SWORD = "SWORD";

        /** 杖: 杖として扱う装備。 */
        public static final String STAFF = "STAFF";

        /** 弓: 弓として扱う装備。 */
        public static final String BOW = "BOW";

        /** ハンマー: ハンマーとして扱う装備。 */
        public static final String HAMMER = "HAMMER";

        /** スピア: スピアとして扱う装備。 */
        public static final String SPEAR = "SPEAR";

        /** ショートボウ: ショートボウとして扱う装備。 */
        public static final String SHORTBOW = "SHORTBOW";

        /** ロングボウ: ロングボウとして扱う装備。 */
        public static final String LONGBOW = "LONGBOW";

        /** ワンド: ワンドとして扱う装備。 */
        public static final String WAND = "WAND";

        /** ツルハシ: 採掘用のツルハシとして扱う装備。 */
        public static final String PICKAXE = "PICKAXE";

        /** 斧: 伐採用の斧として扱う装備。 */
        public static final String AXE = "AXE";

        /** クワ: 採取用のクワとして扱う装備。 */
        public static final String HOE = "HOE";

        /** メインメニュー: 右クリックでメインメニューを開く装備。 */
        public static final String MAIN_MENU = "MAIN_MENU";

        /** カルトグラフ: ダンジョンの現在地図と踏破記録を閲覧する再利用可能な道具。 */
        public static final String CARTOGRAPH = "CARTOGRAPH";

        /** フックショット: フックを装填して固体ブロックへ射出し、使用者を物理的に牽引する道具。 */
        public static final String HOOKSHOT = "HOOKSHOT";
    }

    /** 機能種別タグです。 */
    public static final class Activity {
        private Activity() {
        }

        /** アクティブ: 能動的に発動するスキル。 */
        public static final String ACTIVE = "active";

        /** パッシブ: 常時または条件付きで自動適用されるスキル。 */
        public static final String PASSIVE = "passive";

        /** Mob用: Mob が使用するスキル。 */
        public static final String MOB = "mob";

        /** フィールド: フィールド上の行動・効果に関係する分類。 */
        public static final String FIELD = "field";

        /** ステータス: ステータス効果を持つスキルツリーノード。 */
        public static final String STATUS = "status";

        /** スキルツリー: スキルツリー機能への導線を持つ NPC。 */
        public static final String SKILLTREE = "skilltree";
    }

    /** 戦闘ロールタグです。 */
    public static final class CombatRole {
        private CombatRole() {
        }

        /** 近接: 近接戦闘を主とする分類。 */
        public static final String MELEE = "melee";

        /** 遠隔: 遠隔攻撃を主とする分類。 */
        public static final String RANGED = "ranged";

        /** 魔法: 魔法攻撃または魔法系統の分類。 */
        public static final String MAGIC = "magic";

        /** タンク: 防御と敵対維持を主とするクラスロール。 */
        public static final String TANK = "tank";

        /** アタッカー: ダメージ出力を主とするクラスロール。 */
        public static final String DEALER = "dealer";

        /** バランス: 複数の役割を均等に扱うクラス。 */
        public static final String BALANCED = "balanced";

        /** 防御: 防御能力や耐久力に関係する分類。 */
        public static final String DEFENSE = "defense";

        /** 攻撃: 攻撃能力に関係する分類。 */
        public static final String OFFENSE = "offense";

        /** 前衛: 前線で戦うクラスロール。 */
        public static final String FRONT = "front";

        /** 弓: 弓系統に関係する分類。 */
        public static final String BOW = "bow";

        /** 杖: 杖系統に関係する分類。 */
        public static final String STAFF = "staff";

        /** 剣: 剣系統に関係する分類。 */
        public static final String SWORD = "sword";
    }

    /** 属性タグです。 */
    public static final class Element {
        private Element() {
        }

        /** 炎: 炎属性または炎をモチーフとする分類。 */
        public static final String FIRE = "fire";

        /** 氷: 氷属性に関係する分類。 */
        public static final String ICE = "ice";

        /** 雷: 雷属性に関係する分類。 */
        public static final String LIGHTNING = "lightning";

        /** 毒: 毒属性に関係する分類。 */
        public static final String POISON = "poison";

        /** 光: 光属性に関係する分類。 */
        public static final String LIGHT = "light";

        /** 闇: 闇属性に関係する分類。 */
        public static final String DARK = "dark";

        /** 炎上: 炎上状態に関係する分類。 */
        public static final String BURNING = "burning";

        /** 凍結: 凍結状態に関係する分類。 */
        public static final String FROZEN = "frozen";

        /** 冷却: 冷却状態に関係する分類。 */
        public static final String CHILLED = "chilled";

        /** 感電: 感電状態に関係する分類。 */
        public static final String SHOCKED = "shocked";

        /** 毒状態: 毒状態に関係する分類。 */
        public static final String POISONED = "poisoned";

        /** 盲目: 盲目状態に関係する分類。 */
        public static final String BLINDNESS = "blindness";

        /** 弱体: 弱体状態に関係する分類。 */
        public static final String WEAKNESS = "weakness";

        /** 回復阻害: 回復阻害状態に関係する分類。 */
        public static final String HEALING_INHIBITION = "healing_inhibition";

        /** 状態異常: 状態異常系ノードをまとめる分類。 */
        public static final String CONDITION = "condition";

        /** 属性: 属性系ノードをまとめる分類。 */
        public static final String ELEMENT = "element";
    }

    /** 進行区分タグです。 */
    public static final class Progression {
        private Progression() {
        }

        /** 初期: ゲーム開始時の初期クラス。 */
        public static final String STARTER = "starter";

        /** 初心者: 初心者向けのクラス。 */
        public static final String BEGINNER = "beginner";

        /** 一次職: 一次職段階のクラス。 */
        public static final String TIER1 = "tier1";

        /** 序盤: 序盤に位置するスキルツリーノード。 */
        public static final String EARLY = "early";

        /** 入口: コンテンツ入口への案内を行う NPC。 */
        public static final String ENTRY = "entry";

        /** 帰還: コンテンツからの帰還を案内する NPC。 */
        public static final String RETURN = "return";
    }

    /** スキルツリータグです。 */
    public static final class Skilltree {
        private Skilltree() {
        }

        /** ルート／根: スキルツリーの開始点、または根をモチーフとする分類。 */
        public static final String ROOT = "root";

        /** 共通: 複数クラスで共有するスキルツリーノード。 */
        public static final String SHARED = "shared";

        /** 中核: スキルツリーの中核となるノード。 */
        public static final String CORE = "core";

        /** 基本能力: 基本能力値に関係するノード。 */
        public static final String PRIMARY = "primary";

        /** リソース: HP、MPなどのリソースに関係するノード。 */
        public static final String RESOURCE = "resource";

        /** 筋力: 筋力に関係するノード。 */
        public static final String STRENGTH = "strength";

        /** 敏捷: 敏捷に関係するノード。 */
        public static final String AGILITY = "agility";

        /** 知力: 知力に関係するノード。 */
        public static final String INTELLIGENCE = "intelligence";

        /** 器用: 器用に関係するノード。 */
        public static final String DEXTERITY = "dexterity";

        /** 運: 運に関係するノード。 */
        public static final String LUCK = "luck";

        /** 体力: HPに関係するノード。 */
        public static final String HEALTH = "health";

        /** マナ: MPに関係するノード。 */
        public static final String MANA = "mana";

        /** エネルギー: エネルギーに関係するノード。 */
        public static final String ENERGY = "energy";

        /** シールド: シールド能力または盾を持つ Mob に関係する分類。 */
        public static final String SHIELD = "shield";

        /** 耐久: 耐久力に関係するノード。 */
        public static final String DURABILITY = "durability";

        /** 命中: 命中能力に関係するノード。 */
        public static final String ACCURACY = "accuracy";
    }

    /** 生物・種族タグです。 */
    public static final class Creature {
        private Creature() {
        }

        /** ドラゴン: ドラゴン種の Mob。 */
        public static final String DRAGON = "dragon";

        /** ボス: ボスとして扱う Mob。 */
        public static final String BOSS = "boss";

        /** ゴーレム: ゴーレム種の Mob。 */
        public static final String GOLEM = "golem";

        /** 獣: 獣種の Mob。 */
        public static final String BEAST = "beast";

        /** 精霊: 精霊種の Mob。 */
        public static final String SPIRIT = "spirit";

        /** 守護者: 守護者として配置される Mob。 */
        public static final String GUARDIAN = "guardian";

        /** アンデッド: アンデッド種の Mob。 */
        public static final String UNDEAD = "undead";

        /** スケルトン: スケルトン種の Mob。 */
        public static final String SKELETON = "skeleton";

        /** 人型: 人型の Mob。 */
        public static final String HUMANOID = "humanoid";

        /** ヤギ: ヤギ種の Mob。 */
        public static final String GOAT = "goat";

        /** オオカミ: オオカミ種の Mob。 */
        public static final String WOLF = "wolf";

        /** NPC: NPCとして扱う Mob。 */
        public static final String NPC = "npc";
    }

    /** 地域・環境タグです。 */
    public static final class Location {
        private Location() {
        }

        /** ミズガルズ: ミズガルズ地域に属する分類。 */
        public static final String MIDGARD = "midgard";

        /** 森林: 森林地域に属する分類。 */
        public static final String FOREST = "forest";

        /** 草原: 草原地域に属する分類。 */
        public static final String GRASSLAND = "grassland";

        /** 山岳: 山岳地域に属する分類。 */
        public static final String MOUNTAIN = "mountain";

        /** サバンナ: サバンナ地域に属する分類。 */
        public static final String SAVANNA = "savanna";

        /** アカシア: アカシアをモチーフとする分類。 */
        public static final String ACACIA = "acacia";
    }

    /** NPC役割タグです。 */
    public static final class NpcRole {
        private NpcRole() {
        }

        /** クラス案内: クラス選択を案内する NPC。 */
        public static final String CLASS_GUIDE = "class_guide";

        /** 通貨交換: 通貨交換を提供する NPC。 */
        public static final String CURRENCY_EXCHANGE = "currency_exchange";

        /** 防具店: 防具を扱う店舗 NPC。 */
        public static final String ARMOR_SHOP = "armor_shop";

        /** 武器店: 武器を扱う店舗 NPC。 */
        public static final String WEAPON_SHOP = "weapon_shop";

        /** 店舗: 店舗機能を持つ NPC。 */
        public static final String SHOP = "shop";

        /** 買取: アイテム買取を提供する NPC。 */
        public static final String SELL = "sell";

        /** 倉庫: 倉庫機能を提供する NPC。 */
        public static final String STORAGE = "storage";

        /** ログインボーナス: ログインボーナスを提供する NPC。 */
        public static final String LOGIN_BONUS = "login_bonus";

        /** クエスト発行: クエストを発行する NPC。 */
        public static final String QUEST_GIVER = "quest_giver";
    }

    /** 製作分類タグです。 */
    public static final class Crafting {
        private Crafting() {
        }

        /** 武器: 武器を成果物とするレシピ。 */
        public static final String WEAPON = "weapon";

        /** 防具: 防具を成果物とするレシピ。 */
        public static final String ARMOR = "armor";

        /** 鍛冶: 鍛冶設備や鍛冶工程で扱うレシピ。 */
        public static final String BLACKSMITH = "blacksmith";

        /** 錬金: 錬金・調合工程で扱うレシピ。 */
        public static final String ALCHEMY = "alchemy";

        /** 消耗品: 消耗品を成果物とするレシピ。 */
        public static final String CONSUMABLE = "consumable";
    }

    /** モチーフタグです。 */
    public static final class Theme {
        private Theme() {
        }

        /** 管理者: 管理者専用クラス。 */
        public static final String ADMINISTRATOR = "administrator";

        /** 冒険者: 冒険者クラスと関連スキル。 */
        public static final String ADVENTURER = "adventurer";

        /** コマンド限定: コマンドからのみ利用する分類。 */
        public static final String COMMAND_ONLY = "command-only";

        /** アストラル: 星界をモチーフとする分類。 */
        public static final String ASTRAL = "astral";

        /** 蒼: 蒼色をモチーフとする分類。 */
        public static final String AZURE = "azure";

        /** 残り火: 残り火をモチーフとする分類。 */
        public static final String EMBER = "ember";

        /** 星光: 星の光をモチーフとする分類。 */
        public static final String STARLIGHT = "starlight";

        /** 風: 風をモチーフとする分類。 */
        public static final String WIND = "wind";

        /** 風待ち: 風待ちをモチーフとするスキルまたはMobの分類。 */
        public static final String WINDWAIT = "windwait";

        /** 黄昏: 黄昏をモチーフとする分類。 */
        public static final String TWILIGHT = "twilight";

        /** 苔: 苔をモチーフとする分類。 */
        public static final String MOSS = "moss";

        /** 鉄: 鉄をモチーフとする分類。 */
        public static final String IRON = "iron";

        /** 石: 石をモチーフとする分類。 */
        public static final String STONE = "stone";
    }

    /** 共有タグカタログ由来の表示・適用先情報です。 */
    public record Definition(
        String id,
        String displayName,
        String description,
        String category,
        List<String> appliesTo
    ) {
    }

    private static final Map<String, Definition> DEFINITIONS = Map.ofEntries(
        Map.entry("AMULET", new Definition("AMULET", "アミュレット", "アミュレット用アクセサリ枠へ装着できる装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("TALISMAN", new Definition("TALISMAN", "タリスマン", "タリスマン用アクセサリ枠へ装着できる装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("CHARM", new Definition("CHARM", "チャーム", "チャーム用アクセサリ枠へ装着できる装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("CORE", new Definition("CORE", "コア", "コア用アクセサリ枠へ装着できる装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("RELIC", new Definition("RELIC", "レリック", "レリック用アクセサリ枠へ装着できる装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("SWORD", new Definition("SWORD", "剣", "剣として扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("STAFF", new Definition("STAFF", "杖", "杖として扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("BOW", new Definition("BOW", "弓", "弓として扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("HAMMER", new Definition("HAMMER", "ハンマー", "ハンマーとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("SPEAR", new Definition("SPEAR", "スピア", "スピアとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("SHORTBOW", new Definition("SHORTBOW", "ショートボウ", "ショートボウとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("LONGBOW", new Definition("LONGBOW", "ロングボウ", "ロングボウとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("WAND", new Definition("WAND", "ワンド", "ワンドとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("PICKAXE", new Definition("PICKAXE", "ツルハシ", "採掘用のツルハシとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("AXE", new Definition("AXE", "斧", "伐採用の斧として扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("HOE", new Definition("HOE", "クワ", "採取用のクワとして扱う装備。", "EQUIPMENT", List.of("EQUIPMENT", "GATHERING_REQUIRED_TOOL"))),
        Map.entry("MAIN_MENU", new Definition("MAIN_MENU", "メインメニュー", "右クリックでメインメニューを開く装備。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("CARTOGRAPH", new Definition("CARTOGRAPH", "カルトグラフ", "ダンジョンの現在地図と踏破記録を閲覧する再利用可能な道具。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("HOOKSHOT", new Definition("HOOKSHOT", "フックショット", "フックを装填して固体ブロックへ射出し、使用者を物理的に牽引する道具。", "EQUIPMENT", List.of("EQUIPMENT"))),
        Map.entry("active", new Definition("active", "アクティブ", "能動的に発動するスキル。", "ACTIVITY", List.of("SKILL"))),
        Map.entry("passive", new Definition("passive", "パッシブ", "常時または条件付きで自動適用されるスキル。", "ACTIVITY", List.of("SKILL"))),
        Map.entry("mob", new Definition("mob", "Mob用", "Mob が使用するスキル。", "ACTIVITY", List.of("SKILL"))),
        Map.entry("field", new Definition("field", "フィールド", "フィールド上の行動・効果に関係する分類。", "ACTIVITY", List.of("SKILL"))),
        Map.entry("status", new Definition("status", "ステータス", "ステータス効果を持つスキルツリーノード。", "ACTIVITY", List.of("SKILLTREE_NODE"))),
        Map.entry("skilltree", new Definition("skilltree", "スキルツリー", "スキルツリー機能への導線を持つ NPC。", "ACTIVITY", List.of("MOB"))),
        Map.entry("melee", new Definition("melee", "近接", "近接戦闘を主とする分類。", "COMBAT_ROLE", List.of("CLASS", "SKILL", "MOB"))),
        Map.entry("ranged", new Definition("ranged", "遠隔", "遠隔攻撃を主とする分類。", "COMBAT_ROLE", List.of("CLASS", "SKILL", "MOB"))),
        Map.entry("magic", new Definition("magic", "魔法", "魔法攻撃または魔法系統の分類。", "COMBAT_ROLE", List.of("CLASS", "SKILL", "MOB"))),
        Map.entry("tank", new Definition("tank", "タンク", "防御と敵対維持を主とするクラスロール。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("dealer", new Definition("dealer", "アタッカー", "ダメージ出力を主とするクラスロール。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("balanced", new Definition("balanced", "バランス", "複数の役割を均等に扱うクラス。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("defense", new Definition("defense", "防御", "防御能力や耐久力に関係する分類。", "COMBAT_ROLE", List.of("SKILL", "SKILLTREE_NODE"))),
        Map.entry("offense", new Definition("offense", "攻撃", "攻撃能力に関係する分類。", "COMBAT_ROLE", List.of("SKILLTREE_NODE"))),
        Map.entry("front", new Definition("front", "前衛", "前線で戦うクラスロール。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("bow", new Definition("bow", "弓", "弓系統に関係する分類。", "COMBAT_ROLE", List.of("CLASS", "SKILL"))),
        Map.entry("staff", new Definition("staff", "杖", "杖系統に関係する分類。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("sword", new Definition("sword", "剣", "剣系統に関係する分類。", "COMBAT_ROLE", List.of("CLASS"))),
        Map.entry("fire", new Definition("fire", "炎", "炎属性または炎をモチーフとする分類。", "ELEMENT", List.of("SKILL", "SKILLTREE_NODE", "MOB"))),
        Map.entry("ice", new Definition("ice", "氷", "氷属性に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("lightning", new Definition("lightning", "雷", "雷属性に関係する分類。", "ELEMENT", List.of("SKILL", "SKILLTREE_NODE", "MOB"))),
        Map.entry("poison", new Definition("poison", "毒", "毒属性に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("light", new Definition("light", "光", "光属性に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("dark", new Definition("dark", "闇", "闇属性に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("burning", new Definition("burning", "炎上", "炎上状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("frozen", new Definition("frozen", "凍結", "凍結状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("chilled", new Definition("chilled", "冷却", "冷却状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("shocked", new Definition("shocked", "感電", "感電状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("poisoned", new Definition("poisoned", "毒状態", "毒状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("blindness", new Definition("blindness", "盲目", "盲目状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("weakness", new Definition("weakness", "弱体", "弱体状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("healing_inhibition", new Definition("healing_inhibition", "回復阻害", "回復阻害状態に関係する分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("condition", new Definition("condition", "状態異常", "状態異常系ノードをまとめる分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("element", new Definition("element", "属性", "属性系ノードをまとめる分類。", "ELEMENT", List.of("SKILLTREE_NODE"))),
        Map.entry("starter", new Definition("starter", "初期", "ゲーム開始時の初期クラス。", "PROGRESSION", List.of("CLASS"))),
        Map.entry("beginner", new Definition("beginner", "初心者", "初心者向けのクラス。", "PROGRESSION", List.of("CLASS"))),
        Map.entry("tier1", new Definition("tier1", "一次職", "一次職段階のクラス。", "PROGRESSION", List.of("CLASS"))),
        Map.entry("early", new Definition("early", "序盤", "序盤に位置するスキルツリーノード。", "PROGRESSION", List.of("SKILLTREE_NODE"))),
        Map.entry("entry", new Definition("entry", "入口", "コンテンツ入口への案内を行う NPC。", "PROGRESSION", List.of("MOB"))),
        Map.entry("return", new Definition("return", "帰還", "コンテンツからの帰還を案内する NPC。", "PROGRESSION", List.of("MOB"))),
        Map.entry("root", new Definition("root", "ルート／根", "スキルツリーの開始点、または根をモチーフとする分類。", "SKILLTREE", List.of("SKILLTREE_NODE", "MOB"))),
        Map.entry("shared", new Definition("shared", "共通", "複数クラスで共有するスキルツリーノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("core", new Definition("core", "中核", "スキルツリーの中核となるノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("primary", new Definition("primary", "基本能力", "基本能力値に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("resource", new Definition("resource", "リソース", "HP、MPなどのリソースに関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("strength", new Definition("strength", "筋力", "筋力に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("agility", new Definition("agility", "敏捷", "敏捷に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("intelligence", new Definition("intelligence", "知力", "知力に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("dexterity", new Definition("dexterity", "器用", "器用に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("luck", new Definition("luck", "運", "運に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("health", new Definition("health", "体力", "HPに関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("mana", new Definition("mana", "マナ", "MPに関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("energy", new Definition("energy", "エネルギー", "エネルギーに関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("shield", new Definition("shield", "シールド", "シールド能力または盾を持つ Mob に関係する分類。", "SKILLTREE", List.of("SKILLTREE_NODE", "MOB"))),
        Map.entry("durability", new Definition("durability", "耐久", "耐久力に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("accuracy", new Definition("accuracy", "命中", "命中能力に関係するノード。", "SKILLTREE", List.of("SKILLTREE_NODE"))),
        Map.entry("dragon", new Definition("dragon", "ドラゴン", "ドラゴン種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("boss", new Definition("boss", "ボス", "ボスとして扱う Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("golem", new Definition("golem", "ゴーレム", "ゴーレム種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("beast", new Definition("beast", "獣", "獣種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("spirit", new Definition("spirit", "精霊", "精霊種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("guardian", new Definition("guardian", "守護者", "守護者として配置される Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("undead", new Definition("undead", "アンデッド", "アンデッド種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("skeleton", new Definition("skeleton", "スケルトン", "スケルトン種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("humanoid", new Definition("humanoid", "人型", "人型の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("goat", new Definition("goat", "ヤギ", "ヤギ種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("wolf", new Definition("wolf", "オオカミ", "オオカミ種の Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("npc", new Definition("npc", "NPC", "NPCとして扱う Mob。", "CREATURE", List.of("MOB"))),
        Map.entry("midgard", new Definition("midgard", "ミズガルズ", "ミズガルズ地域に属する分類。", "LOCATION", List.of("MOB", "RECIPE"))),
        Map.entry("forest", new Definition("forest", "森林", "森林地域に属する分類。", "LOCATION", List.of("MOB"))),
        Map.entry("grassland", new Definition("grassland", "草原", "草原地域に属する分類。", "LOCATION", List.of("MOB"))),
        Map.entry("mountain", new Definition("mountain", "山岳", "山岳地域に属する分類。", "LOCATION", List.of("SKILL", "MOB"))),
        Map.entry("savanna", new Definition("savanna", "サバンナ", "サバンナ地域に属する分類。", "LOCATION", List.of("SKILL", "MOB"))),
        Map.entry("acacia", new Definition("acacia", "アカシア", "アカシアをモチーフとする分類。", "LOCATION", List.of("MOB"))),
        Map.entry("class_guide", new Definition("class_guide", "クラス案内", "クラス選択を案内する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("currency_exchange", new Definition("currency_exchange", "通貨交換", "通貨交換を提供する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("armor_shop", new Definition("armor_shop", "防具店", "防具を扱う店舗 NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("weapon_shop", new Definition("weapon_shop", "武器店", "武器を扱う店舗 NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("shop", new Definition("shop", "店舗", "店舗機能を持つ NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("sell", new Definition("sell", "買取", "アイテム買取を提供する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("storage", new Definition("storage", "倉庫", "倉庫機能を提供する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("login_bonus", new Definition("login_bonus", "ログインボーナス", "ログインボーナスを提供する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("quest_giver", new Definition("quest_giver", "クエスト発行", "クエストを発行する NPC。", "NPC_ROLE", List.of("MOB"))),
        Map.entry("weapon", new Definition("weapon", "武器", "武器を成果物とするレシピ。", "CRAFTING", List.of("RECIPE"))),
        Map.entry("armor", new Definition("armor", "防具", "防具を成果物とするレシピ。", "CRAFTING", List.of("RECIPE"))),
        Map.entry("blacksmith", new Definition("blacksmith", "鍛冶", "鍛冶設備や鍛冶工程で扱うレシピ。", "CRAFTING", List.of("RECIPE"))),
        Map.entry("alchemy", new Definition("alchemy", "錬金", "錬金・調合工程で扱うレシピ。", "CRAFTING", List.of("RECIPE"))),
        Map.entry("consumable", new Definition("consumable", "消耗品", "消耗品を成果物とするレシピ。", "CRAFTING", List.of("RECIPE"))),
        Map.entry("administrator", new Definition("administrator", "管理者", "管理者専用クラス。", "THEME", List.of("CLASS"))),
        Map.entry("adventurer", new Definition("adventurer", "冒険者", "冒険者クラスと関連スキル。", "THEME", List.of("CLASS", "SKILL"))),
        Map.entry("command-only", new Definition("command-only", "コマンド限定", "コマンドからのみ利用する分類。", "THEME", List.of("CLASS"))),
        Map.entry("astral", new Definition("astral", "アストラル", "星界をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE"))),
        Map.entry("azure", new Definition("azure", "蒼", "蒼色をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE"))),
        Map.entry("ember", new Definition("ember", "残り火", "残り火をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE"))),
        Map.entry("starlight", new Definition("starlight", "星光", "星の光をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE"))),
        Map.entry("wind", new Definition("wind", "風", "風をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE"))),
        Map.entry("windwait", new Definition("windwait", "風待ち", "風待ちをモチーフとするスキルまたはMobの分類。", "THEME", List.of("SKILL", "MOB"))),
        Map.entry("twilight", new Definition("twilight", "黄昏", "黄昏をモチーフとする分類。", "THEME", List.of("MOB"))),
        Map.entry("moss", new Definition("moss", "苔", "苔をモチーフとする分類。", "THEME", List.of("MOB"))),
        Map.entry("iron", new Definition("iron", "鉄", "鉄をモチーフとする分類。", "THEME", List.of("MOB"))),
        Map.entry("stone", new Definition("stone", "石", "石をモチーフとする分類。", "THEME", List.of("SKILLTREE_NODE", "MOB")))
    );

    /** 不変IDに対応する共有タグ定義を取得します。 */
    public static Definition find(String id) {
        return DEFINITIONS.get(id);
    }
}
