// <auto-generated>
// 40_filebase/76.shared.tag/v1.tags.yml から生成されます。直接編集しないでください。
// </auto-generated>

package io.github.maaasu.astralRecord.shared.masterdata.tag;

/** 共有タグカタログから生成されたタグID定数です。 */
public final class MasterTagIds {
    private MasterTagIds() {
    }

    /** 装備種別タグです。 */
    public static final class Equipment {
        private Equipment() {
        }

        /** アミュレット: アミュレット用アクセサリ枠へ装着できる装備。 */
        public static final String AMULET = "AMULET";

        /** タリスマン: タリスマン用アクセサリ枠へ装着できる装備。 */
        public static final String TALISMAN = "TALISMAN";

        /** チャーム: チャーム用アクセサリ枠へ装着できる装備。 */
        public static final String CHARM = "CHARM";

        /** コア: コア用アクセサリ枠へ装着できる装備。 */
        public static final String CORE = "CORE";

        /** レリック: レリック用アクセサリ枠へ装着できる装備。 */
        public static final String RELIC = "RELIC";

        /** 剣: 剣として扱う装備。 */
        public static final String SWORD = "SWORD";

        /** 杖: 杖として扱う装備。 */
        public static final String STAFF = "STAFF";

        /** 弓: 弓として扱う装備。 */
        public static final String BOW = "BOW";

        /** ツルハシ: 採掘用のツルハシとして扱う装備。 */
        public static final String PICKAXE = "PICKAXE";

        /** 斧: 伐採用の斧として扱う装備。 */
        public static final String AXE = "AXE";

        /** クワ: 採取用のクワとして扱う装備。 */
        public static final String HOE = "HOE";
    }

    /** 機能種別タグです。 */
    public static final class Activity {
        private Activity() {
        }

        /** アクティブ: 能動的に発動するスキル。 */
        public static final String ACTIVE = "active";

        /** パッシブ: 常時または条件付きで自動適用されるスキル。 */
        public static final String PASSIVE = "passive";

        /** Mob用: Mob が使用するスキル。 */
        public static final String MOB = "mob";

        /** フィールド: フィールド上の行動・効果に関係する分類。 */
        public static final String FIELD = "field";

        /** ステータス: ステータス効果を持つスキルツリーノード。 */
        public static final String STATUS = "status";

        /** スキルツリー: スキルツリー機能への導線を持つ NPC。 */
        public static final String SKILLTREE = "skilltree";
    }

    /** 戦闘ロールタグです。 */
    public static final class CombatRole {
        private CombatRole() {
        }

        /** 近接: 近接戦闘を主とする分類。 */
        public static final String MELEE = "melee";

        /** 遠隔: 遠隔攻撃を主とする分類。 */
        public static final String RANGED = "ranged";

        /** 魔法: 魔法攻撃または魔法系統の分類。 */
        public static final String MAGIC = "magic";

        /** タンク: 防御と敵対維持を主とするクラスロール。 */
        public static final String TANK = "tank";

        /** アタッカー: ダメージ出力を主とするクラスロール。 */
        public static final String DEALER = "dealer";

        /** バランス: 複数の役割を均等に扱うクラス。 */
        public static final String BALANCED = "balanced";

        /** 防御: 防御能力や耐久力に関係する分類。 */
        public static final String DEFENSE = "defense";

        /** 攻撃: 攻撃能力に関係する分類。 */
        public static final String OFFENSE = "offense";

        /** 弓: 弓系統に関係する分類。 */
        public static final String BOW = "bow";

        /** 杖: 杖系統に関係する分類。 */
        public static final String STAFF = "staff";

        /** 剣: 剣系統に関係する分類。 */
        public static final String SWORD = "sword";
    }

    /** 属性タグです。 */
    public static final class Element {
        private Element() {
        }

        /** 炎: 炎属性または炎をモチーフとする分類。 */
        public static final String FIRE = "fire";

        /** 氷: 氷属性に関係する分類。 */
        public static final String ICE = "ice";

        /** 雷: 雷属性に関係する分類。 */
        public static final String LIGHTNING = "lightning";

        /** 毒: 毒属性に関係する分類。 */
        public static final String POISON = "poison";

        /** 光: 光属性に関係する分類。 */
        public static final String LIGHT = "light";

        /** 闇: 闇属性に関係する分類。 */
        public static final String DARK = "dark";

        /** 炎上: 炎上状態に関係する分類。 */
        public static final String BURNING = "burning";

        /** 凍結: 凍結状態に関係する分類。 */
        public static final String FROZEN = "frozen";

        /** 冷却: 冷却状態に関係する分類。 */
        public static final String CHILLED = "chilled";

        /** 感電: 感電状態に関係する分類。 */
        public static final String SHOCKED = "shocked";

        /** 毒状態: 毒状態に関係する分類。 */
        public static final String POISONED = "poisoned";

        /** 盲目: 盲目状態に関係する分類。 */
        public static final String BLINDNESS = "blindness";

        /** 弱体: 弱体状態に関係する分類。 */
        public static final String WEAKNESS = "weakness";

        /** 回復阻害: 回復阻害状態に関係する分類。 */
        public static final String HEALING_INHIBITION = "healing_inhibition";

        /** 状態異常: 状態異常系ノードをまとめる分類。 */
        public static final String CONDITION = "condition";

        /** 属性: 属性系ノードをまとめる分類。 */
        public static final String ELEMENT = "element";
    }

    /** 進行区分タグです。 */
    public static final class Progression {
        private Progression() {
        }

        /** 初期: ゲーム開始時の初期クラス。 */
        public static final String STARTER = "starter";

        /** 初心者: 初心者向けのクラス。 */
        public static final String BEGINNER = "beginner";

        /** 一次職: 一次職段階のクラス。 */
        public static final String TIER1 = "tier1";

        /** 序盤: 序盤に位置するスキルツリーノード。 */
        public static final String EARLY = "early";

        /** 入口: コンテンツ入口への案内を行う NPC。 */
        public static final String ENTRY = "entry";

        /** 帰還: コンテンツからの帰還を案内する NPC。 */
        public static final String RETURN = "return";
    }

    /** スキルツリータグです。 */
    public static final class Skilltree {
        private Skilltree() {
        }

        /** ルート／根: スキルツリーの開始点、または根をモチーフとする分類。 */
        public static final String ROOT = "root";

        /** 共通: 複数クラスで共有するスキルツリーノード。 */
        public static final String SHARED = "shared";

        /** 中核: スキルツリーの中核となるノード。 */
        public static final String CORE = "core";

        /** 基本能力: 基本能力値に関係するノード。 */
        public static final String PRIMARY = "primary";

        /** リソース: HP、MPなどのリソースに関係するノード。 */
        public static final String RESOURCE = "resource";

        /** 筋力: 筋力に関係するノード。 */
        public static final String STRENGTH = "strength";

        /** 敏捷: 敏捷に関係するノード。 */
        public static final String AGILITY = "agility";

        /** 知力: 知力に関係するノード。 */
        public static final String INTELLIGENCE = "intelligence";

        /** 器用: 器用に関係するノード。 */
        public static final String DEXTERITY = "dexterity";

        /** 運: 運に関係するノード。 */
        public static final String LUCK = "luck";

        /** 体力: HPに関係するノード。 */
        public static final String HEALTH = "health";

        /** マナ: MPに関係するノード。 */
        public static final String MANA = "mana";

        /** エネルギー: エネルギーに関係するノード。 */
        public static final String ENERGY = "energy";

        /** シールド: シールド能力または盾を持つ Mob に関係する分類。 */
        public static final String SHIELD = "shield";

        /** 耐久: 耐久力に関係するノード。 */
        public static final String DURABILITY = "durability";

        /** 命中: 命中能力に関係するノード。 */
        public static final String ACCURACY = "accuracy";
    }

    /** 生物・種族タグです。 */
    public static final class Creature {
        private Creature() {
        }

        /** ドラゴン: ドラゴン種の Mob。 */
        public static final String DRAGON = "dragon";

        /** ボス: ボスとして扱う Mob。 */
        public static final String BOSS = "boss";

        /** ゴーレム: ゴーレム種の Mob。 */
        public static final String GOLEM = "golem";

        /** 獣: 獣種の Mob。 */
        public static final String BEAST = "beast";

        /** 精霊: 精霊種の Mob。 */
        public static final String SPIRIT = "spirit";

        /** 守護者: 守護者として配置される Mob。 */
        public static final String GUARDIAN = "guardian";

        /** アンデッド: アンデッド種の Mob。 */
        public static final String UNDEAD = "undead";

        /** スケルトン: スケルトン種の Mob。 */
        public static final String SKELETON = "skeleton";

        /** 人型: 人型の Mob。 */
        public static final String HUMANOID = "humanoid";

        /** ヤギ: ヤギ種の Mob。 */
        public static final String GOAT = "goat";

        /** オオカミ: オオカミ種の Mob。 */
        public static final String WOLF = "wolf";

        /** NPC: NPCとして扱う Mob。 */
        public static final String NPC = "npc";
    }

    /** 地域・環境タグです。 */
    public static final class Location {
        private Location() {
        }

        /** ミズガルズ: ミズガルズ地域に属する分類。 */
        public static final String MIDGARD = "midgard";

        /** 森林: 森林地域に属する分類。 */
        public static final String FOREST = "forest";

        /** 草原: 草原地域に属する分類。 */
        public static final String GRASSLAND = "grassland";

        /** 山岳: 山岳地域に属する分類。 */
        public static final String MOUNTAIN = "mountain";

        /** サバンナ: サバンナ地域に属する分類。 */
        public static final String SAVANNA = "savanna";

        /** アカシア: アカシアをモチーフとする分類。 */
        public static final String ACACIA = "acacia";
    }

    /** NPC役割タグです。 */
    public static final class NpcRole {
        private NpcRole() {
        }

        /** クラス案内: クラス選択を案内する NPC。 */
        public static final String CLASS_GUIDE = "class_guide";

        /** 通貨交換: 通貨交換を提供する NPC。 */
        public static final String CURRENCY_EXCHANGE = "currency_exchange";

        /** 装備強化: 装備強化を提供する NPC。 */
        public static final String EQUIPMENT_ENHANCE = "equipment_enhance";

        /** 装備修理: 装備修理を提供する NPC。 */
        public static final String EQUIPMENT_REPAIR = "equipment_repair";

        /** 防具店: 防具を扱う店舗 NPC。 */
        public static final String ARMOR_SHOP = "armor_shop";

        /** 武器店: 武器を扱う店舗 NPC。 */
        public static final String WEAPON_SHOP = "weapon_shop";

        /** 店舗: 店舗機能を持つ NPC。 */
        public static final String SHOP = "shop";

        /** 買取: アイテム買取を提供する NPC。 */
        public static final String SELL = "sell";

        /** 倉庫: 倉庫機能を提供する NPC。 */
        public static final String STORAGE = "storage";

        /** ログインボーナス: ログインボーナスを提供する NPC。 */
        public static final String LOGIN_BONUS = "login_bonus";

        /** クエスト発行: クエストを発行する NPC。 */
        public static final String QUEST_GIVER = "quest_giver";
    }

    /** 製作分類タグです。 */
    public static final class Crafting {
        private Crafting() {
        }

        /** 武器: 武器を成果物とするレシピ。 */
        public static final String WEAPON = "weapon";

        /** 防具: 防具を成果物とするレシピ。 */
        public static final String ARMOR = "armor";
    }

    /** モチーフタグです。 */
    public static final class Theme {
        private Theme() {
        }

        /** 管理者: 管理者専用クラス。 */
        public static final String ADMINISTRATOR = "administrator";

        /** 冒険者: 冒険者クラス。 */
        public static final String ADVENTURER = "adventurer";

        /** コマンド限定: コマンドからのみ利用する分類。 */
        public static final String COMMAND_ONLY = "command-only";

        /** アストラル: 星界をモチーフとする分類。 */
        public static final String ASTRAL = "astral";

        /** 蒼: 蒼色をモチーフとする分類。 */
        public static final String AZURE = "azure";

        /** 残り火: 残り火をモチーフとする分類。 */
        public static final String EMBER = "ember";

        /** 星光: 星の光をモチーフとする分類。 */
        public static final String STARLIGHT = "starlight";

        /** 風: 風をモチーフとする分類。 */
        public static final String WIND = "wind";

        /** 風待ち: 風待ちをモチーフとするスキル分類。 */
        public static final String WINDWAIT = "windwait";

        /** 黄昏: 黄昏をモチーフとする分類。 */
        public static final String TWILIGHT = "twilight";

        /** 苔: 苔をモチーフとする分類。 */
        public static final String MOSS = "moss";

        /** 鉄: 鉄をモチーフとする分類。 */
        public static final String IRON = "iron";

        /** 石: 石をモチーフとする分類。 */
        public static final String STONE = "stone";
    }
}
