name: AstralRecord
version: ${project.version}
main: io.github.maaasu.astralRecord.AstralRecord
api-version: '1.21'
authors: [ "AstralRecord" ]
depend: [ProtocolLib]
softdepend: [DiscordSRV]

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
