// <auto-generated>
// 40_filebase/75.shared.status/v1.status_types.yml から生成されます。直接編集しないでください。
// </auto-generated>
package io.github.maaasu.astralRecord.feature.status.model

import io.github.maaasu.astralRecord.infrastructure.util.ColorCodeUtil
import net.kyori.adventure.text.format.NamedTextColor
import java.util.Locale

/** 共有ステータスカタログから生成されたステータス種別です。 */
enum class StatusType(
    val id: String,
    val displayName: String,
    val category: Category,
    val suffix: String = "",
    val decimalPlaces: Int = 0,
    val supportsRange: Boolean = true,
) {
    MAX_HEALTH("MAX_HEALTH", "最大HP", Category.RESOURCE, "", 0, false),
    MAX_MANA("MAX_MANA", "最大MP", Category.RESOURCE, "", 0, false),
    MAX_ENERGY("MAX_ENERGY", "最大EN", Category.RESOURCE, "", 0, false),
    MAX_SHIELD("MAX_SHIELD", "最大シールド", Category.RESOURCE, "", 0, false),
    STRENGTH("STRENGTH", "筋力", Category.PRIMARY, "", 0, true),
    DEXTERITY("DEXTERITY", "器用さ", Category.PRIMARY, "", 0, true),
    INTELLIGENCE("INTELLIGENCE", "知力", Category.PRIMARY, "", 0, true),
    VITALITY("VITALITY", "体力", Category.PRIMARY, "", 0, true),
    AGILITY("AGILITY", "敏捷性", Category.PRIMARY, "", 0, true),
    LUCK("LUCK", "幸運", Category.PRIMARY, "", 0, true),
    ATTACK("ATTACK", "攻撃力", Category.OFFENSE, "", 0, true),
    MELEE_ATTACK("MELEE_ATTACK", "近接攻撃力", Category.OFFENSE, "", 0, true),
    RANGED_ATTACK("RANGED_ATTACK", "間接攻撃力", Category.OFFENSE, "", 0, true),
    MAGIC_ATTACK("MAGIC_ATTACK", "魔法攻撃力", Category.OFFENSE, "", 0, true),
    CRITICAL_RATE("CRITICAL_RATE", "会心率", Category.OFFENSE, "%", 1, true),
    CRITICAL_DAMAGE("CRITICAL_DAMAGE", "会心ダメージ", Category.OFFENSE, "%", 1, true),
    SUPER_CRITICAL_RATE("SUPER_CRITICAL_RATE", "超会心率", Category.OFFENSE, "%", 1, true),
    SUPER_CRITICAL_DAMAGE("SUPER_CRITICAL_DAMAGE", "超会心ダメージ", Category.OFFENSE, "%", 1, true),
    FINAL_DAMAGE_RATE("FINAL_DAMAGE_RATE", "最終ダメージ確率", Category.OFFENSE, "%", 1, true),
    FINAL_DAMAGE_MULTIPLIER("FINAL_DAMAGE_MULTIPLIER", "最終ダメージ倍率", Category.OFFENSE, "%", 1, true),
    ACCURACY("ACCURACY", "命中率", Category.OFFENSE, "%", 1, true),
    ATTACK_SPEED("ATTACK_SPEED", "攻撃速度", Category.OFFENSE, "%", 0, true),
    SHIELD_BREAK("SHIELD_BREAK", "シールドブレイク", Category.OFFENSE, "", 0, true),
    FIRE_DAMAGE_INCREASE("FIRE_DAMAGE_INCREASE", "火属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    FIRE_RESISTANCE("FIRE_RESISTANCE", "火属性耐性", Category.ELEMENT, "%", 1, true),
    FIRE_PENETRATION("FIRE_PENETRATION", "火属性貫通", Category.ELEMENT, "%", 1, true),
    ICE_DAMAGE_INCREASE("ICE_DAMAGE_INCREASE", "氷属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    ICE_RESISTANCE("ICE_RESISTANCE", "氷属性耐性", Category.ELEMENT, "%", 1, true),
    ICE_PENETRATION("ICE_PENETRATION", "氷属性貫通", Category.ELEMENT, "%", 1, true),
    LIGHTNING_DAMAGE_INCREASE("LIGHTNING_DAMAGE_INCREASE", "雷属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    LIGHTNING_RESISTANCE("LIGHTNING_RESISTANCE", "雷属性耐性", Category.ELEMENT, "%", 1, true),
    LIGHTNING_PENETRATION("LIGHTNING_PENETRATION", "雷属性貫通", Category.ELEMENT, "%", 1, true),
    POISON_DAMAGE_INCREASE("POISON_DAMAGE_INCREASE", "毒属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    POISON_RESISTANCE("POISON_RESISTANCE", "毒属性耐性", Category.ELEMENT, "%", 1, true),
    POISON_PENETRATION("POISON_PENETRATION", "毒属性貫通", Category.ELEMENT, "%", 1, true),
    LIGHT_DAMAGE_INCREASE("LIGHT_DAMAGE_INCREASE", "光属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    LIGHT_RESISTANCE("LIGHT_RESISTANCE", "光属性耐性", Category.ELEMENT, "%", 1, true),
    LIGHT_PENETRATION("LIGHT_PENETRATION", "光属性貫通", Category.ELEMENT, "%", 1, true),
    DARK_DAMAGE_INCREASE("DARK_DAMAGE_INCREASE", "闇属性ダメージ増加", Category.ELEMENT, "%", 1, true),
    DARK_RESISTANCE("DARK_RESISTANCE", "闇属性耐性", Category.ELEMENT, "%", 1, true),
    DARK_PENETRATION("DARK_PENETRATION", "闇属性貫通", Category.ELEMENT, "%", 1, true),
    BURNING_APPLY_CHANCE("BURNING_APPLY_CHANCE", "燃焼付与確率増加", Category.CONDITION, "%", 1, true),
    BURNING_RESISTANCE("BURNING_RESISTANCE", "燃焼付与耐性", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_INCREASE("BURNING_DAMAGE_INCREASE", "燃焼ダメージ増加", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_RESISTANCE("BURNING_DAMAGE_RESISTANCE", "燃焼ダメージ耐性", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_PENETRATION("BURNING_DAMAGE_PENETRATION", "燃焼DoT貫通", Category.CONDITION, "%", 1, true),
    FROZEN_APPLY_CHANCE("FROZEN_APPLY_CHANCE", "凍結付与確率増加", Category.CONDITION, "%", 1, true),
    FROZEN_RESISTANCE("FROZEN_RESISTANCE", "凍結付与耐性", Category.CONDITION, "%", 1, true),
    CHILLED_APPLY_CHANCE("CHILLED_APPLY_CHANCE", "冷気付与確率増加", Category.CONDITION, "%", 1, true),
    CHILLED_RESISTANCE("CHILLED_RESISTANCE", "冷気付与耐性", Category.CONDITION, "%", 1, true),
    SHOCKED_APPLY_CHANCE("SHOCKED_APPLY_CHANCE", "感電付与確率増加", Category.CONDITION, "%", 1, true),
    SHOCKED_RESISTANCE("SHOCKED_RESISTANCE", "感電付与耐性", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_INCREASE("SHOCKED_DAMAGE_INCREASE", "感電ダメージ増加", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_RESISTANCE("SHOCKED_DAMAGE_RESISTANCE", "感電ダメージ耐性", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_PENETRATION("SHOCKED_DAMAGE_PENETRATION", "感電DoT貫通", Category.CONDITION, "%", 1, true),
    POISONED_APPLY_CHANCE("POISONED_APPLY_CHANCE", "毒状態付与確率増加", Category.CONDITION, "%", 1, true),
    POISONED_RESISTANCE("POISONED_RESISTANCE", "毒状態付与耐性", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_INCREASE("POISONED_DAMAGE_INCREASE", "毒状態ダメージ増加", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_RESISTANCE("POISONED_DAMAGE_RESISTANCE", "毒状態ダメージ耐性", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_PENETRATION("POISONED_DAMAGE_PENETRATION", "毒状態DoT貫通", Category.CONDITION, "%", 1, true),
    BLINDNESS_APPLY_CHANCE("BLINDNESS_APPLY_CHANCE", "盲目付与確率増加", Category.CONDITION, "%", 1, true),
    BLINDNESS_RESISTANCE("BLINDNESS_RESISTANCE", "盲目付与耐性", Category.CONDITION, "%", 1, true),
    WEAKNESS_APPLY_CHANCE("WEAKNESS_APPLY_CHANCE", "衰弱付与確率増加", Category.CONDITION, "%", 1, true),
    WEAKNESS_RESISTANCE("WEAKNESS_RESISTANCE", "衰弱付与耐性", Category.CONDITION, "%", 1, true),
    HEALING_INHIBITION_APPLY_CHANCE("HEALING_INHIBITION_APPLY_CHANCE", "回復阻害付与確率増加", Category.CONDITION, "%", 1, true),
    HEALING_INHIBITION_RESISTANCE("HEALING_INHIBITION_RESISTANCE", "回復阻害付与耐性", Category.CONDITION, "%", 1, true),
    DEFENSE("DEFENSE", "防御力", Category.DEFENSE, "", 0, true),
    MAGIC_DEFENSE("MAGIC_DEFENSE", "魔法防御力", Category.DEFENSE, "", 0, true),
    EVASION("EVASION", "回避率", Category.DEFENSE, "%", 1, true),
    KNOCKBACK_RESISTANCE("KNOCKBACK_RESISTANCE", "ノックバック耐性", Category.DEFENSE, "%", 1, true),
    HP_REGEN("HP_REGEN", "HP回復力", Category.UTILITY, "", 0, true),
    MP_REGEN("MP_REGEN", "MP回復力", Category.UTILITY, "", 0, true),
    ENERGY_REGEN("ENERGY_REGEN", "EN回復力", Category.UTILITY, "", 0, true),
    MOVEMENT_SPEED("MOVEMENT_SPEED", "移動速度", Category.UTILITY, "", 0, true),
    COOLDOWN_REDUCTION("COOLDOWN_REDUCTION", "CD短縮", Category.UTILITY, "%", 1, true),
    SHIELD_RECHARGE_REDUCTION("SHIELD_RECHARGE_REDUCTION", "シールドリチャージ短縮", Category.UTILITY, "%", 1, true),
    SHIELD_RECHARGE_RATE("SHIELD_RECHARGE_RATE", "シールドリチャージ", Category.UTILITY, "", 0, true),
    MINING_SPEED("MINING_SPEED", "採集速度", Category.UTILITY, "", 0, true),
    INVENTORY_SLOTS("INVENTORY_SLOTS", "インベントリスロット", Category.UTILITY, "", 0, false),
    QUEST_LIMIT("QUEST_LIMIT", "クエスト受領上限", Category.UTILITY, "", 0, false),
    ;

    /** 共有ステータスカテゴリです。 */
    enum class Category(val displayName: String) {
        RESOURCE("リソース"),
        PRIMARY("基本能力値"),
        OFFENSE("攻撃"),
        DEFENSE("防御"),
        ELEMENT("属性"),
        CONDITION("状態異常"),
        UTILITY("ユーティリティ"),
    }

    /**
     * ステータス値をsuffix付きの表示用文字列へ変換します。
     *
     * @param value 表示対象の値
     * @return カタログで定義された小数桁数とsuffixを適用した文字列
     */
    fun formatValue(value: Double): String =
        String.format(Locale.US, "%,.${decimalPlaces}f", value) + suffix

    /**
     * `%`単位で表示するステータスかどうかを返します。
     *
     * @return suffixが`%`の場合はtrue
     */
    fun isPercentage(): Boolean = suffix == "%"

    /**
     * 正の値へ`+`を付けた補正表示へ変換します。
     *
     * @param value 表示対象の補正値
     * @return 符号とsuffixを含む表示用文字列
     */
    fun formatSignedValue(value: Double): String = (if (value > 0.0) "+" else "") + formatValue(value)

    /**
     * 同値なら単一値、それ以外なら最小値と最大値を表示します。
     *
     * @param minValue 表示する下限
     * @param maxValue 表示する上限
     * @return 単一値または範囲文字列
     */
    fun formatRange(minValue: Double, maxValue: Double): String =
        if (minValue == maxValue) formatValue(minValue) else "${formatValue(minValue)} ～ ${formatValue(maxValue)}"

    /**
     * 同値なら単一補正、それ以外なら符号付き範囲を表示します。
     *
     * @param minValue 表示する補正下限
     * @param maxValue 表示する補正上限
     * @return 符号付きの単一値または範囲文字列
     */
    fun formatSignedRange(minValue: Double, maxValue: Double): String =
        if (minValue == maxValue) formatSignedValue(minValue)
        else "${formatSignedValue(minValue)} ～ ${formatSignedValue(maxValue)}"

    /**
     * Plugin UIで使う共通表示色を返します。
     *
     * @return カテゴリに対応するAdventure色
     */
    fun namedColor(): NamedTextColor = when (category) {
        Category.RESOURCE -> NamedTextColor.GOLD
        Category.PRIMARY -> NamedTextColor.GREEN
        Category.OFFENSE -> NamedTextColor.RED
        Category.DEFENSE -> NamedTextColor.BLUE
        Category.ELEMENT -> NamedTextColor.LIGHT_PURPLE
        Category.CONDITION -> NamedTextColor.DARK_PURPLE
        Category.UTILITY -> NamedTextColor.YELLOW
    }

    /**
     * Plugin UIで使うlegacy color codeを返します。
     *
     * @return カテゴリに対応するlegacy color code
     */
    fun legacyColor(): String = when (category) {
        Category.RESOURCE -> ColorCodeUtil.GOLD
        Category.PRIMARY -> ColorCodeUtil.GREEN
        Category.OFFENSE -> ColorCodeUtil.RED
        Category.DEFENSE -> ColorCodeUtil.BLUE
        Category.ELEMENT -> ColorCodeUtil.LIGHT_PURPLE
        Category.CONDITION -> ColorCodeUtil.DARK_PURPLE
        Category.UTILITY -> ColorCodeUtil.YELLOW
    }

    companion object {
        private val byId = entries.associateBy(StatusType::id)

        /**
         * 指定カテゴリに属するステータスを返します。
         *
         * @param category 対象カテゴリ
         * @return 対象カテゴリのステータス一覧
         */
        @JvmStatic
        fun byCategory(category: Category): List<StatusType> = entries.filter { it.category == category }

        /**
         * 不変IDに対応するステータスを返します。
         *
         * @param id 大文字スネークケースの不変ID
         * @return 対応するステータス。未定義の場合はnull
         */
        @JvmStatic
        fun fromId(id: String): StatusType? = byId[id]
    }
}
