// <auto-generated>
// 40_filebase/75.shared.status/v1.status_types.yml から生成されます。直接編集しないでください。
// </auto-generated>
package io.github.maaasu.astralRecord.feature.status.model

import io.github.maaasu.astralRecord.infrastructure.util.ColorCodeUtil
import net.kyori.adventure.text.format.NamedTextColor
import java.util.Locale

/** 共有ステータスカタログから生成されたステータス種別です。 */
enum class StatusType(
    val id: String,
    val displayName: String,
    val description: String,
    val category: Category,
    val suffix: String = "",
    val decimalPlaces: Int = 0,
    val supportsRange: Boolean = true,
) {
    MAX_HEALTH("MAX_HEALTH", "最大HP", "戦闘不能になるまでに耐えられるダメージ量の上限。", Category.RESOURCE, "", 0, false),
    MAX_MANA("MAX_MANA", "最大MP", "スキルや魔法の使用に充てられるMPの上限。", Category.RESOURCE, "", 0, false),
    MAX_ENERGY("MAX_ENERGY", "最大ENG", "特殊行動やスキルの使用に充てられるENGの上限。", Category.RESOURCE, "", 0, false),
    MAX_SHIELD("MAX_SHIELD", "最大シールド", "HPとは別にダメージを受け止めるシールド量の上限。最大シールドの獲得にはタンクシールドアクティベートの習得と使用許可が必要。", Category.RESOURCE, "", 0, false),
    STRENGTH("STRENGTH", "筋力", "物理的な攻撃能力を表す基本能力値。", Category.PRIMARY, "", 0, true),
    DEXTERITY("DEXTERITY", "器用さ", "攻撃や行動を正確に扱う技量を表す基本能力値。", Category.PRIMARY, "", 0, true),
    INTELLIGENCE("INTELLIGENCE", "知力", "魔法や知識を扱う能力を表す基本能力値。", Category.PRIMARY, "", 0, true),
    VITALITY("VITALITY", "体力", "肉体の頑健さと生命力を表す基本能力値。", Category.PRIMARY, "", 0, true),
    AGILITY("AGILITY", "敏捷性", "素早く動き、危険を避ける能力を表す基本能力値。", Category.PRIMARY, "", 0, true),
    LUCK("LUCK", "幸運", "有利な結果を引き寄せる運の強さを表す基本能力値。", Category.PRIMARY, "", 0, true),
    ATTACK("ATTACK", "攻撃力", "物理・魔法を含む攻撃の基礎となる総合的な威力。", Category.OFFENSE, "", 0, true),
    MELEE_ATTACK("MELEE_ATTACK", "近接攻撃力", "近距離で行う物理攻撃の威力。", Category.OFFENSE, "", 0, true),
    RANGED_ATTACK("RANGED_ATTACK", "間接攻撃力", "距離を取って行う射撃などの攻撃の威力。", Category.OFFENSE, "", 0, true),
    MAGIC_ATTACK("MAGIC_ATTACK", "魔法攻撃力", "魔法による攻撃の威力。", Category.OFFENSE, "", 0, true),
    CRITICAL_RATE("CRITICAL_RATE", "会心率", "攻撃が会心になる確率。", Category.OFFENSE, "%", 1, true),
    CRITICAL_DAMAGE("CRITICAL_DAMAGE", "会心ダメージ", "会心が発生したときのダメージ倍率。", Category.OFFENSE, "%", 1, true),
    SUPER_CRITICAL_RATE("SUPER_CRITICAL_RATE", "超星会心率", "プレイヤーの攻撃が超星会心になる確率。", Category.OFFENSE, "%", 1, true),
    SUPER_CRITICAL_DAMAGE("SUPER_CRITICAL_DAMAGE", "超星会心倍率", "主攻撃では100%へ加算し、追尾弾ではそのまま乗算する超星会心の割合。", Category.OFFENSE, "%", 1, true),
    SKILL_DAMAGE_INCREASE("SKILL_DAMAGE_INCREASE", "スキルダメージ増加", "スキルで与えるダメージを増加させる補正。", Category.OFFENSE, "%", 1, true),
    NORMAL_ATTACK_DAMAGE_INCREASE("NORMAL_ATTACK_DAMAGE_INCREASE", "通常攻撃ダメージ増加", "通常攻撃で与えるダメージを増加させる補正。", Category.OFFENSE, "%", 1, true),
    FINAL_DAMAGE_MULTIPLIER("FINAL_DAMAGE_MULTIPLIER", "最終ダメージ倍率", "各種補正の後に常時適用される最終ダメージ倍率。", Category.OFFENSE, "%", 1, true),
    ACCURACY("ACCURACY", "命中率", "攻撃が対象へ命中する確率。", Category.OFFENSE, "%", 1, true),
    ATTACK_SPEED("ATTACK_SPEED", "攻撃速度", "通常攻撃や攻撃行動を行う速さ。", Category.OFFENSE, "%", 0, true),
    SHIELD_BREAK("SHIELD_BREAK", "シールドブレイク", "対象のシールドを削る攻撃性能。", Category.OFFENSE, "", 0, true),
    FIXED_HEALTH_DAMAGE("FIXED_HEALTH_DAMAGE", "HP固定ダメージ", "直接攻撃の命中時に、防御・会心・属性・最終ダメージ倍率を無視してHPへ加算するダメージ。シールド有効中は発生しない。", Category.OFFENSE, "", 0, true),
    SHIELD_RECHARGE_DELAY_CHANCE("SHIELD_RECHARGE_DELAY_CHANCE", "シールドリチャージ加算率", "直接攻撃時に対象のシールドリチャージ時間を延長する確率。", Category.OFFENSE, "%", 1, true),
    SHIELD_RECHARGE_DELAY_SECONDS("SHIELD_RECHARGE_DELAY_SECONDS", "シールドリチャージ加算値", "シールドリチャージ加算率の抽選成功時に対象へ追加する基礎秒数。", Category.OFFENSE, "秒", 1, true),
    DEFENSE_PENETRATION_RATE("DEFENSE_PENETRATION_RATE", "防御力貫通率", "対象の全ダメージ防御力を割合で無視する補正。", Category.OFFENSE, "%", 1, true),
    MELEE_DEFENSE_PENETRATION_RATE("MELEE_DEFENSE_PENETRATION_RATE", "近接防御貫通率", "対象の近接防御力を割合で無視する補正。", Category.OFFENSE, "%", 1, true),
    RANGED_DEFENSE_PENETRATION_RATE("RANGED_DEFENSE_PENETRATION_RATE", "間接防御貫通率", "対象の間接防御力を割合で無視する補正。", Category.OFFENSE, "%", 1, true),
    MAGIC_DEFENSE_PENETRATION_RATE("MAGIC_DEFENSE_PENETRATION_RATE", "魔法防御貫通率", "対象の魔法防御力を割合で無視する補正。", Category.OFFENSE, "%", 1, true),
    LIFE_STEAL("LIFE_STEAL", "ライフスティール", "HPへ与えたダメージの一部を自身のHPとして回復する補正。", Category.OFFENSE, "%", 1, true),
    FIRE_DAMAGE_INCREASE("FIRE_DAMAGE_INCREASE", "火属性ダメージ増加", "火属性で与えるダメージを増加させる補正。", Category.ELEMENT, "%", 1, true),
    FIRE_RESISTANCE("FIRE_RESISTANCE", "火属性耐性", "火属性から受けるダメージを軽減する補正。", Category.ELEMENT, "%", 1, true),
    FIRE_RESISTANCE_CAP("FIRE_RESISTANCE_CAP", "火属性耐性上限値", "火属性耐性として計算できる上限値。", Category.ELEMENT, "%", 1, true),
    FIRE_PENETRATION("FIRE_PENETRATION", "火属性貫通", "対象の火属性耐性を無視して攻撃する性能。", Category.ELEMENT, "%", 1, true),
    ICE_DAMAGE_INCREASE("ICE_DAMAGE_INCREASE", "氷属性ダメージ増加", "氷属性で与えるダメージを増加させる補正。", Category.ELEMENT, "%", 1, true),
    ICE_RESISTANCE("ICE_RESISTANCE", "氷属性耐性", "氷属性から受けるダメージを軽減する補正。", Category.ELEMENT, "%", 1, true),
    ICE_RESISTANCE_CAP("ICE_RESISTANCE_CAP", "氷属性耐性上限値", "氷属性耐性として計算できる上限値。", Category.ELEMENT, "%", 1, true),
    ICE_PENETRATION("ICE_PENETRATION", "氷属性貫通", "対象の氷属性耐性を無視して攻撃する性能。", Category.ELEMENT, "%", 1, true),
    LIGHTNING_DAMAGE_INCREASE("LIGHTNING_DAMAGE_INCREASE", "雷属性ダメージ増加", "雷属性で与えるダメージを増加させる補正。", Category.ELEMENT, "%", 1, true),
    LIGHTNING_RESISTANCE("LIGHTNING_RESISTANCE", "雷属性耐性", "雷属性から受けるダメージを軽減する補正。", Category.ELEMENT, "%", 1, true),
    LIGHTNING_RESISTANCE_CAP("LIGHTNING_RESISTANCE_CAP", "雷属性耐性上限値", "雷属性耐性として計算できる上限値。", Category.ELEMENT, "%", 1, true),
    LIGHTNING_PENETRATION("LIGHTNING_PENETRATION", "雷属性貫通", "対象の雷属性耐性を無視して攻撃する性能。", Category.ELEMENT, "%", 1, true),
    BURNING_APPLY_CHANCE("BURNING_APPLY_CHANCE", "燃焼付与確率増加", "攻撃時に燃焼を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    BURNING_RESISTANCE("BURNING_RESISTANCE", "燃焼付与耐性", "燃焼を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_INCREASE("BURNING_DAMAGE_INCREASE", "燃焼ダメージ増加", "燃焼によって与える継続ダメージを増加させる補正。", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_RESISTANCE("BURNING_DAMAGE_RESISTANCE", "燃焼ダメージ耐性", "燃焼によって受ける継続ダメージを軽減する補正。", Category.CONDITION, "%", 1, true),
    BURNING_DAMAGE_PENETRATION("BURNING_DAMAGE_PENETRATION", "燃焼DoT貫通", "燃焼の継続ダメージに対する耐性を貫通する性能。", Category.CONDITION, "%", 1, true),
    FROZEN_APPLY_CHANCE("FROZEN_APPLY_CHANCE", "凍結付与確率増加", "攻撃時に凍結を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    FROZEN_RESISTANCE("FROZEN_RESISTANCE", "凍結付与耐性", "凍結を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    CHILLED_APPLY_CHANCE("CHILLED_APPLY_CHANCE", "冷気付与確率増加", "攻撃時に冷気を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    CHILLED_RESISTANCE("CHILLED_RESISTANCE", "冷気付与耐性", "冷気を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    SHOCKED_APPLY_CHANCE("SHOCKED_APPLY_CHANCE", "感電付与確率増加", "攻撃時に感電を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    SHOCKED_RESISTANCE("SHOCKED_RESISTANCE", "感電付与耐性", "感電を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_INCREASE("SHOCKED_DAMAGE_INCREASE", "感電ダメージ増加", "感電によって与える継続ダメージを増加させる補正。", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_RESISTANCE("SHOCKED_DAMAGE_RESISTANCE", "感電ダメージ耐性", "感電によって受ける継続ダメージを軽減する補正。", Category.CONDITION, "%", 1, true),
    SHOCKED_DAMAGE_PENETRATION("SHOCKED_DAMAGE_PENETRATION", "感電DoT貫通", "感電の継続ダメージに対する耐性を貫通する性能。", Category.CONDITION, "%", 1, true),
    POISONED_APPLY_CHANCE("POISONED_APPLY_CHANCE", "毒状態付与確率増加", "攻撃時に毒状態を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    POISONED_RESISTANCE("POISONED_RESISTANCE", "毒状態付与耐性", "毒状態を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_INCREASE("POISONED_DAMAGE_INCREASE", "毒状態ダメージ増加", "毒状態によって与える継続ダメージを増加させる補正。", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_RESISTANCE("POISONED_DAMAGE_RESISTANCE", "毒状態ダメージ耐性", "毒状態によって受ける継続ダメージを軽減する補正。", Category.CONDITION, "%", 1, true),
    POISONED_DAMAGE_PENETRATION("POISONED_DAMAGE_PENETRATION", "毒状態DoT貫通", "毒状態の継続ダメージに対する耐性を貫通する性能。", Category.CONDITION, "%", 1, true),
    BLINDNESS_APPLY_CHANCE("BLINDNESS_APPLY_CHANCE", "盲目付与確率増加", "攻撃時に盲目を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    BLINDNESS_RESISTANCE("BLINDNESS_RESISTANCE", "盲目付与耐性", "盲目を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    WEAKNESS_APPLY_CHANCE("WEAKNESS_APPLY_CHANCE", "衰弱付与確率増加", "攻撃時に衰弱を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    WEAKNESS_RESISTANCE("WEAKNESS_RESISTANCE", "衰弱付与耐性", "衰弱を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    HEALING_INHIBITION_APPLY_CHANCE("HEALING_INHIBITION_APPLY_CHANCE", "回復阻害付与確率増加", "攻撃時に回復阻害を付与する確率を高める補正。", Category.CONDITION, "%", 1, true),
    HEALING_INHIBITION_RESISTANCE("HEALING_INHIBITION_RESISTANCE", "回復阻害付与耐性", "回復阻害を付与されにくくする補正。", Category.CONDITION, "%", 1, true),
    DEFENSE("DEFENSE", "防御力", "すべての攻撃種別から受けるダメージを抑える共通防御力。", Category.DEFENSE, "", 0, true),
    MELEE_DEFENSE("MELEE_DEFENSE", "近接防御力", "近接攻撃から受けるダメージを追加で抑える防御性能。", Category.DEFENSE, "", 0, true),
    RANGED_DEFENSE("RANGED_DEFENSE", "間接防御力", "間接攻撃から受けるダメージを追加で抑える防御性能。", Category.DEFENSE, "", 0, true),
    MAGIC_DEFENSE("MAGIC_DEFENSE", "魔法防御力", "魔法攻撃から受けるダメージを追加で抑える防御性能。", Category.DEFENSE, "", 0, true),
    EVASION("EVASION", "回避率", "攻撃を回避して無効化する確率。", Category.DEFENSE, "%", 1, true),
    KNOCKBACK_RESISTANCE("KNOCKBACK_RESISTANCE", "ノックバック耐性", "攻撃を受けたときにノックバックしにくくする補正。", Category.DEFENSE, "%", 1, true),
    HP_REGEN("HP_REGEN", "HP回復力", "時間経過などでHPを回復する量。", Category.UTILITY, "", 0, true),
    MP_REGEN("MP_REGEN", "MP回復力", "時間経過などでMPを回復する量。", Category.UTILITY, "", 0, true),
    ENERGY_REGEN("ENERGY_REGEN", "ENG回復力", "時間経過などでENGを回復する量。", Category.UTILITY, "", 0, true),
    MOVEMENT_SPEED("MOVEMENT_SPEED", "移動速度", "フィールド上を移動する速さ。", Category.UTILITY, "", 0, true),
    MOVEMENT_SPEED_CAP("MOVEMENT_SPEED_CAP", "移動速度上限", "通常状態で適用できる移動速度の上限。", Category.UTILITY, "", 0, false),
    COOLDOWN_REDUCTION("COOLDOWN_REDUCTION", "クールダウン短縮", "スキルの再使用までに必要な時間を短縮する補正。", Category.UTILITY, "%", 1, true),
    CAST_TIME_REDUCTION("CAST_TIME_REDUCTION", "詠唱時間短縮率", "スキルの詠唱時間を割合で短縮する補正。", Category.UTILITY, "%", 1, true),
    MANA_COST_REDUCTION("MANA_COST_REDUCTION", "MP消費軽減率", "スキルのMP消費量を割合で軽減する補正。", Category.UTILITY, "%", 1, true),
    ENERGY_COST_REDUCTION("ENERGY_COST_REDUCTION", "エネルギー消費軽減率", "スキルのエネルギー消費量を割合で軽減する補正。", Category.UTILITY, "%", 1, true),
    SUPPORT_POWER("SUPPORT_POWER", "支援力", "回復や支援系状態異常の基礎効果を高める能力。", Category.UTILITY, "", 0, true),
    HEALING_INCREASE("HEALING_INCREASE", "回復量増加", "自身のHP回復量を増加させる補正。", Category.UTILITY, "%", 1, true),
    CONDITION_DURATION_INCREASE("CONDITION_DURATION_INCREASE", "状態異常持続時間増加", "自身が付与する状態異常の持続時間を増加させる補正。", Category.UTILITY, "%", 1, true),
    SHIELD_RECHARGE_REDUCTION("SHIELD_RECHARGE_REDUCTION", "シールドリチャージ短縮", "シールド破壊後のリチャージ時間、再充填パッシブの待機時間、攻撃による追加時間を割合で短縮する補正。", Category.UTILITY, "%", 1, true),
    MINING_SPEED("MINING_SPEED", "採集速度", "採掘や採取などの採集行動を行う速さ。", Category.UTILITY, "", 0, true),
    INVENTORY_SLOTS("INVENTORY_SLOTS", "インベントリスロット", "アイテムを保持できるインベントリの枠数。", Category.UTILITY, "", 0, false),
    PASSIVE_SKILL_SLOTS("PASSIVE_SKILL_SLOTS", "パッシブスキルスロット", "基礎5枠へ加算されるパッシブスキルの有効枠数。1ポイントごとに1枠増加し、合計9枠を上限とする。", Category.UTILITY, "", 0, false),
    QUEST_LIMIT("QUEST_LIMIT", "クエスト受領上限", "同時に受領できるクエスト数の上限。", Category.UTILITY, "", 0, false),
    ;

    /** 共有ステータスカテゴリです。 */
    enum class Category(val displayName: String) {
        RESOURCE("リソース"),
        PRIMARY("基本能力値"),
        OFFENSE("攻撃"),
        DEFENSE("防御"),
        ELEMENT("属性"),
        CONDITION("状態異常"),
        UTILITY("ユーティリティ"),
    }

    /**
     * ステータス値をsuffix付きの表示用文字列へ変換します。
     *
     * @param value 表示対象の値
     * @return カタログで定義された小数桁数とsuffixを適用した文字列
     */
    fun formatValue(value: Double): String =
        String.format(Locale.US, "%,.${decimalPlaces}f", value) + suffix

    /**
     * `%`単位で表示するステータスかどうかを返します。
     *
     * @return suffixが`%`の場合はtrue
     */
    fun isPercentage(): Boolean = suffix == "%"

    /**
     * 正の値へ`+`を付けた補正表示へ変換します。
     *
     * @param value 表示対象の補正値
     * @return 符号とsuffixを含む表示用文字列
     */
    fun formatSignedValue(value: Double): String = (if (value > 0.0) "+" else "") + formatValue(value)

    /**
     * 同値なら単一値、それ以外なら最小値と最大値を表示します。
     *
     * @param minValue 表示する下限
     * @param maxValue 表示する上限
     * @return 単一値または範囲文字列
     */
    fun formatRange(minValue: Double, maxValue: Double): String =
        if (minValue == maxValue) formatValue(minValue) else "${formatValue(minValue)}～${formatValue(maxValue)}"

    /**
     * 同値なら単一補正、それ以外なら符号付き範囲を表示します。
     *
     * @param minValue 表示する補正下限
     * @param maxValue 表示する補正上限
     * @return 符号付きの単一値または範囲文字列
     */
    fun formatSignedRange(minValue: Double, maxValue: Double): String =
        if (minValue == maxValue) formatSignedValue(minValue)
        else "${formatSignedValue(minValue)}～${formatSignedValue(maxValue)}"

    /**
     * Plugin UIで使う共通表示色を返します。
     *
     * @return カテゴリに対応するAdventure色
     */
    fun namedColor(): NamedTextColor = when (category) {
        Category.RESOURCE -> NamedTextColor.GOLD
        Category.PRIMARY -> NamedTextColor.GREEN
        Category.OFFENSE -> NamedTextColor.RED
        Category.DEFENSE -> NamedTextColor.BLUE
        Category.ELEMENT -> NamedTextColor.LIGHT_PURPLE
        Category.CONDITION -> NamedTextColor.DARK_PURPLE
        Category.UTILITY -> NamedTextColor.YELLOW
    }

    /**
     * Plugin UIで使うlegacy color codeを返します。
     *
     * @return カテゴリに対応するlegacy color code
     */
    fun legacyColor(): String = when (category) {
        Category.RESOURCE -> ColorCodeUtil.GOLD
        Category.PRIMARY -> ColorCodeUtil.GREEN
        Category.OFFENSE -> ColorCodeUtil.RED
        Category.DEFENSE -> ColorCodeUtil.BLUE
        Category.ELEMENT -> ColorCodeUtil.LIGHT_PURPLE
        Category.CONDITION -> ColorCodeUtil.DARK_PURPLE
        Category.UTILITY -> ColorCodeUtil.YELLOW
    }

    companion object {
        private val byId = entries.associateBy(StatusType::id)

        /**
         * 指定カテゴリに属するステータスを返します。
         *
         * @param category 対象カテゴリ
         * @return 対象カテゴリのステータス一覧
         */
        @JvmStatic
        fun byCategory(category: Category): List<StatusType> = entries.filter { it.category == category }

        /**
         * 不変IDに対応するステータスを返します。
         *
         * @param id 大文字スネークケースの不変ID
         * @return 対応するステータス。未定義の場合はnull
         */
        @JvmStatic
        fun fromId(id: String): StatusType? = byId[id]
    }
}
