// <auto-generated>
// 40_filebase/75.shared.status/v1.status_types.yml から生成されます。直接編集しないでください。
// </auto-generated>

export const STATUS_TYPE_IDS = [
  "MAX_HEALTH",
  "MAX_MANA",
  "MAX_ENERGY",
  "MAX_SHIELD",
  "STRENGTH",
  "DEXTERITY",
  "INTELLIGENCE",
  "VITALITY",
  "AGILITY",
  "LUCK",
  "ATTACK",
  "MELEE_ATTACK",
  "RANGED_ATTACK",
  "MAGIC_ATTACK",
  "CRITICAL_RATE",
  "CRITICAL_DAMAGE",
  "SUPER_CRITICAL_RATE",
  "SUPER_CRITICAL_DAMAGE",
  "FINAL_DAMAGE_RATE",
  "FINAL_DAMAGE_MULTIPLIER",
  "ACCURACY",
  "ATTACK_SPEED",
  "SHIELD_BREAK",
  "FIRE_DAMAGE_INCREASE",
  "FIRE_RESISTANCE",
  "FIRE_PENETRATION",
  "ICE_DAMAGE_INCREASE",
  "ICE_RESISTANCE",
  "ICE_PENETRATION",
  "LIGHTNING_DAMAGE_INCREASE",
  "LIGHTNING_RESISTANCE",
  "LIGHTNING_PENETRATION",
  "POISON_DAMAGE_INCREASE",
  "POISON_RESISTANCE",
  "POISON_PENETRATION",
  "LIGHT_DAMAGE_INCREASE",
  "LIGHT_RESISTANCE",
  "LIGHT_PENETRATION",
  "DARK_DAMAGE_INCREASE",
  "DARK_RESISTANCE",
  "DARK_PENETRATION",
  "BURNING_APPLY_CHANCE",
  "BURNING_RESISTANCE",
  "BURNING_DAMAGE_INCREASE",
  "BURNING_DAMAGE_RESISTANCE",
  "BURNING_DAMAGE_PENETRATION",
  "FROZEN_APPLY_CHANCE",
  "FROZEN_RESISTANCE",
  "CHILLED_APPLY_CHANCE",
  "CHILLED_RESISTANCE",
  "SHOCKED_APPLY_CHANCE",
  "SHOCKED_RESISTANCE",
  "SHOCKED_DAMAGE_INCREASE",
  "SHOCKED_DAMAGE_RESISTANCE",
  "SHOCKED_DAMAGE_PENETRATION",
  "POISONED_APPLY_CHANCE",
  "POISONED_RESISTANCE",
  "POISONED_DAMAGE_INCREASE",
  "POISONED_DAMAGE_RESISTANCE",
  "POISONED_DAMAGE_PENETRATION",
  "BLINDNESS_APPLY_CHANCE",
  "BLINDNESS_RESISTANCE",
  "WEAKNESS_APPLY_CHANCE",
  "WEAKNESS_RESISTANCE",
  "HEALING_INHIBITION_APPLY_CHANCE",
  "HEALING_INHIBITION_RESISTANCE",
  "DEFENSE",
  "MAGIC_DEFENSE",
  "EVASION",
  "KNOCKBACK_RESISTANCE",
  "HP_REGEN",
  "MP_REGEN",
  "ENERGY_REGEN",
  "MOVEMENT_SPEED",
  "COOLDOWN_REDUCTION",
  "SHIELD_RECHARGE_REDUCTION",
  "SHIELD_RECHARGE_RATE",
  "MINING_SPEED",
  "INVENTORY_SLOTS",
  "QUEST_LIMIT",
] as const

export type StatusTypeId = typeof STATUS_TYPE_IDS[number]

export type StatusCategoryId = "RESOURCE" | "PRIMARY" | "OFFENSE" | "DEFENSE" | "ELEMENT" | "CONDITION" | "UTILITY"

export interface StatusTypeDefinition {
  readonly id: StatusTypeId
  readonly displayName: string
  readonly category: StatusCategoryId
  readonly suffix: string
  readonly decimalPlaces: number
  readonly supportsRange: boolean
}

export const STATUS_TYPES: readonly StatusTypeDefinition[] = [
  { id: "MAX_HEALTH", displayName: "最大HP", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_MANA", displayName: "最大MP", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_ENERGY", displayName: "最大EN", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_SHIELD", displayName: "最大シールド", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "STRENGTH", displayName: "筋力", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "DEXTERITY", displayName: "器用さ", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "INTELLIGENCE", displayName: "知力", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "VITALITY", displayName: "体力", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "AGILITY", displayName: "敏捷性", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "LUCK", displayName: "幸運", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "ATTACK", displayName: "攻撃力", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MELEE_ATTACK", displayName: "近接攻撃力", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "RANGED_ATTACK", displayName: "間接攻撃力", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MAGIC_ATTACK", displayName: "魔法攻撃力", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "CRITICAL_RATE", displayName: "会心率", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CRITICAL_DAMAGE", displayName: "会心ダメージ", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SUPER_CRITICAL_RATE", displayName: "超会心率", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SUPER_CRITICAL_DAMAGE", displayName: "超会心ダメージ", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FINAL_DAMAGE_RATE", displayName: "最終ダメージ確率", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FINAL_DAMAGE_MULTIPLIER", displayName: "最終ダメージ倍率", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ACCURACY", displayName: "命中率", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ATTACK_SPEED", displayName: "攻撃速度", category: "OFFENSE", suffix: "%", decimalPlaces: 0, supportsRange: true },
  { id: "SHIELD_BREAK", displayName: "シールドブレイク", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "FIRE_DAMAGE_INCREASE", displayName: "火属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FIRE_RESISTANCE", displayName: "火属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FIRE_PENETRATION", displayName: "火属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_DAMAGE_INCREASE", displayName: "氷属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_RESISTANCE", displayName: "氷属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_PENETRATION", displayName: "氷属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_DAMAGE_INCREASE", displayName: "雷属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_RESISTANCE", displayName: "雷属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_PENETRATION", displayName: "雷属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_DAMAGE_INCREASE", displayName: "毒属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_RESISTANCE", displayName: "毒属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_PENETRATION", displayName: "毒属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_DAMAGE_INCREASE", displayName: "光属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_RESISTANCE", displayName: "光属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_PENETRATION", displayName: "光属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_DAMAGE_INCREASE", displayName: "闇属性ダメージ増加", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_RESISTANCE", displayName: "闇属性耐性", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_PENETRATION", displayName: "闇属性貫通", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_APPLY_CHANCE", displayName: "燃焼付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_RESISTANCE", displayName: "燃焼付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_INCREASE", displayName: "燃焼ダメージ増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_RESISTANCE", displayName: "燃焼ダメージ耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_PENETRATION", displayName: "燃焼DoT貫通", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FROZEN_APPLY_CHANCE", displayName: "凍結付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FROZEN_RESISTANCE", displayName: "凍結付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CHILLED_APPLY_CHANCE", displayName: "冷気付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CHILLED_RESISTANCE", displayName: "冷気付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_APPLY_CHANCE", displayName: "感電付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_RESISTANCE", displayName: "感電付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_INCREASE", displayName: "感電ダメージ増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_RESISTANCE", displayName: "感電ダメージ耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_PENETRATION", displayName: "感電DoT貫通", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_APPLY_CHANCE", displayName: "毒状態付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_RESISTANCE", displayName: "毒状態付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_INCREASE", displayName: "毒状態ダメージ増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_RESISTANCE", displayName: "毒状態ダメージ耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_PENETRATION", displayName: "毒状態DoT貫通", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BLINDNESS_APPLY_CHANCE", displayName: "盲目付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BLINDNESS_RESISTANCE", displayName: "盲目付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "WEAKNESS_APPLY_CHANCE", displayName: "衰弱付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "WEAKNESS_RESISTANCE", displayName: "衰弱付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HEALING_INHIBITION_APPLY_CHANCE", displayName: "回復阻害付与確率増加", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HEALING_INHIBITION_RESISTANCE", displayName: "回復阻害付与耐性", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DEFENSE", displayName: "防御力", category: "DEFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MAGIC_DEFENSE", displayName: "魔法防御力", category: "DEFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "EVASION", displayName: "回避率", category: "DEFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "KNOCKBACK_RESISTANCE", displayName: "ノックバック耐性", category: "DEFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HP_REGEN", displayName: "HP回復力", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MP_REGEN", displayName: "MP回復力", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "ENERGY_REGEN", displayName: "EN回復力", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MOVEMENT_SPEED", displayName: "移動速度", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "COOLDOWN_REDUCTION", displayName: "CD短縮", category: "UTILITY", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHIELD_RECHARGE_REDUCTION", displayName: "シールドリチャージ短縮", category: "UTILITY", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHIELD_RECHARGE_RATE", displayName: "シールドリチャージ", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MINING_SPEED", displayName: "採集速度", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "INVENTORY_SLOTS", displayName: "インベントリスロット", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "QUEST_LIMIT", displayName: "クエスト受領上限", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: false },
]

export const STATUS_TYPE_BY_ID = new Map<StatusTypeId, StatusTypeDefinition>(
  STATUS_TYPES.map((status) => [status.id, status]),
)

export function isStatusTypeId(value: string): value is StatusTypeId {
  return STATUS_TYPE_BY_ID.has(value as StatusTypeId)
}

export function formatStatusValue(status: StatusTypeDefinition, value: number): string {
  return `${value.toLocaleString('en-US', {
    minimumFractionDigits: status.decimalPlaces,
    maximumFractionDigits: status.decimalPlaces,
  })}${status.suffix}`
}

export function formatStatusModifier(
  status: StatusTypeDefinition,
  modifierType: string,
  value: number,
): string {
  if (modifierType === 'SCALAR') {
    const percentage = value * 100
    const formatted = percentage.toLocaleString('en-US', { maximumFractionDigits: 2 })
    return `${percentage > 0 ? '+' : ''}${formatted}%`
  }
  return `${value > 0 ? '+' : ''}${formatStatusValue(status, value)}`
}
