// <auto-generated>
// 40_filebase/75.shared.status/v1.status_types.yml から生成されます。直接編集しないでください。
// </auto-generated>

export const STATUS_TYPE_IDS = [
  "MAX_HEALTH",
  "MAX_MANA",
  "MAX_ENERGY",
  "MAX_SHIELD",
  "STRENGTH",
  "DEXTERITY",
  "INTELLIGENCE",
  "VITALITY",
  "AGILITY",
  "LUCK",
  "ATTACK",
  "MELEE_ATTACK",
  "RANGED_ATTACK",
  "MAGIC_ATTACK",
  "CRITICAL_RATE",
  "CRITICAL_DAMAGE",
  "SUPER_CRITICAL_RATE",
  "SUPER_CRITICAL_DAMAGE",
  "FINAL_DAMAGE_RATE",
  "FINAL_DAMAGE_MULTIPLIER",
  "ACCURACY",
  "ATTACK_SPEED",
  "SHIELD_BREAK",
  "FIRE_DAMAGE_INCREASE",
  "FIRE_RESISTANCE",
  "FIRE_PENETRATION",
  "ICE_DAMAGE_INCREASE",
  "ICE_RESISTANCE",
  "ICE_PENETRATION",
  "LIGHTNING_DAMAGE_INCREASE",
  "LIGHTNING_RESISTANCE",
  "LIGHTNING_PENETRATION",
  "POISON_DAMAGE_INCREASE",
  "POISON_RESISTANCE",
  "POISON_PENETRATION",
  "LIGHT_DAMAGE_INCREASE",
  "LIGHT_RESISTANCE",
  "LIGHT_PENETRATION",
  "DARK_DAMAGE_INCREASE",
  "DARK_RESISTANCE",
  "DARK_PENETRATION",
  "BURNING_APPLY_CHANCE",
  "BURNING_RESISTANCE",
  "BURNING_DAMAGE_INCREASE",
  "BURNING_DAMAGE_RESISTANCE",
  "BURNING_DAMAGE_PENETRATION",
  "FROZEN_APPLY_CHANCE",
  "FROZEN_RESISTANCE",
  "CHILLED_APPLY_CHANCE",
  "CHILLED_RESISTANCE",
  "SHOCKED_APPLY_CHANCE",
  "SHOCKED_RESISTANCE",
  "SHOCKED_DAMAGE_INCREASE",
  "SHOCKED_DAMAGE_RESISTANCE",
  "SHOCKED_DAMAGE_PENETRATION",
  "POISONED_APPLY_CHANCE",
  "POISONED_RESISTANCE",
  "POISONED_DAMAGE_INCREASE",
  "POISONED_DAMAGE_RESISTANCE",
  "POISONED_DAMAGE_PENETRATION",
  "BLINDNESS_APPLY_CHANCE",
  "BLINDNESS_RESISTANCE",
  "WEAKNESS_APPLY_CHANCE",
  "WEAKNESS_RESISTANCE",
  "HEALING_INHIBITION_APPLY_CHANCE",
  "HEALING_INHIBITION_RESISTANCE",
  "DEFENSE",
  "MAGIC_DEFENSE",
  "EVASION",
  "KNOCKBACK_RESISTANCE",
  "HP_REGEN",
  "MP_REGEN",
  "ENERGY_REGEN",
  "MOVEMENT_SPEED",
  "COOLDOWN_REDUCTION",
  "SHIELD_RECHARGE_REDUCTION",
  "SHIELD_RECHARGE_RATE",
  "MINING_SPEED",
  "INVENTORY_SLOTS",
  "QUEST_LIMIT",
] as const

export type StatusTypeId = typeof STATUS_TYPE_IDS[number]

export type StatusCategoryId = "RESOURCE" | "PRIMARY" | "OFFENSE" | "DEFENSE" | "ELEMENT" | "CONDITION" | "UTILITY"

export interface StatusTypeDefinition {
  readonly id: StatusTypeId
  readonly displayName: string
  readonly description: string
  readonly category: StatusCategoryId
  readonly suffix: string
  readonly decimalPlaces: number
  readonly supportsRange: boolean
}

export const STATUS_TYPES: readonly StatusTypeDefinition[] = [
  { id: "MAX_HEALTH", displayName: "最大HP", description: "戦闘不能になるまでに耐えられるダメージ量の上限。", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_MANA", displayName: "最大MP", description: "スキルや魔法の使用に充てられるMPの上限。", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_ENERGY", displayName: "最大EN", description: "特殊行動やスキルの使用に充てられるENの上限。", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "MAX_SHIELD", displayName: "最大シールド", description: "HPとは別にダメージを受け止めるシールド量の上限。", category: "RESOURCE", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "STRENGTH", displayName: "筋力", description: "物理的な攻撃能力を表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "DEXTERITY", displayName: "器用さ", description: "攻撃や行動を正確に扱う技量を表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "INTELLIGENCE", displayName: "知力", description: "魔法や知識を扱う能力を表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "VITALITY", displayName: "体力", description: "肉体の頑健さと生命力を表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "AGILITY", displayName: "敏捷性", description: "素早く動き、危険を避ける能力を表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "LUCK", displayName: "幸運", description: "有利な結果を引き寄せる運の強さを表す基本能力値。", category: "PRIMARY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "ATTACK", displayName: "攻撃力", description: "物理・魔法を含む攻撃の基礎となる総合的な威力。", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MELEE_ATTACK", displayName: "近接攻撃力", description: "近距離で行う物理攻撃の威力。", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "RANGED_ATTACK", displayName: "間接攻撃力", description: "距離を取って行う射撃などの攻撃の威力。", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MAGIC_ATTACK", displayName: "魔法攻撃力", description: "魔法による攻撃の威力。", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "CRITICAL_RATE", displayName: "会心率", description: "攻撃が会心になる確率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CRITICAL_DAMAGE", displayName: "会心ダメージ", description: "会心が発生したときのダメージ倍率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SUPER_CRITICAL_RATE", displayName: "超会心率", description: "攻撃が超会心になる確率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SUPER_CRITICAL_DAMAGE", displayName: "超会心ダメージ", description: "超会心が発生したときのダメージ倍率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FINAL_DAMAGE_RATE", displayName: "最終ダメージ確率", description: "最終ダメージ補正が適用される確率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FINAL_DAMAGE_MULTIPLIER", displayName: "最終ダメージ倍率", description: "各種補正の後に最終的に適用されるダメージ倍率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ACCURACY", displayName: "命中率", description: "攻撃が対象へ命中する確率。", category: "OFFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ATTACK_SPEED", displayName: "攻撃速度", description: "通常攻撃や攻撃行動を行う速さ。", category: "OFFENSE", suffix: "%", decimalPlaces: 0, supportsRange: true },
  { id: "SHIELD_BREAK", displayName: "シールドブレイク", description: "対象のシールドを削る攻撃性能。", category: "OFFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "FIRE_DAMAGE_INCREASE", displayName: "火属性ダメージ増加", description: "火属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FIRE_RESISTANCE", displayName: "火属性耐性", description: "火属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FIRE_PENETRATION", displayName: "火属性貫通", description: "対象の火属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_DAMAGE_INCREASE", displayName: "氷属性ダメージ増加", description: "氷属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_RESISTANCE", displayName: "氷属性耐性", description: "氷属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "ICE_PENETRATION", displayName: "氷属性貫通", description: "対象の氷属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_DAMAGE_INCREASE", displayName: "雷属性ダメージ増加", description: "雷属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_RESISTANCE", displayName: "雷属性耐性", description: "雷属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHTNING_PENETRATION", displayName: "雷属性貫通", description: "対象の雷属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_DAMAGE_INCREASE", displayName: "毒属性ダメージ増加", description: "毒属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_RESISTANCE", displayName: "毒属性耐性", description: "毒属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISON_PENETRATION", displayName: "毒属性貫通", description: "対象の毒属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_DAMAGE_INCREASE", displayName: "光属性ダメージ増加", description: "光属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_RESISTANCE", displayName: "光属性耐性", description: "光属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "LIGHT_PENETRATION", displayName: "光属性貫通", description: "対象の光属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_DAMAGE_INCREASE", displayName: "闇属性ダメージ増加", description: "闇属性で与えるダメージを増加させる補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_RESISTANCE", displayName: "闇属性耐性", description: "闇属性から受けるダメージを軽減する補正。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DARK_PENETRATION", displayName: "闇属性貫通", description: "対象の闇属性耐性を無視して攻撃する性能。", category: "ELEMENT", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_APPLY_CHANCE", displayName: "燃焼付与確率増加", description: "攻撃時に燃焼を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_RESISTANCE", displayName: "燃焼付与耐性", description: "燃焼を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_INCREASE", displayName: "燃焼ダメージ増加", description: "燃焼によって与える継続ダメージを増加させる補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_RESISTANCE", displayName: "燃焼ダメージ耐性", description: "燃焼によって受ける継続ダメージを軽減する補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BURNING_DAMAGE_PENETRATION", displayName: "燃焼DoT貫通", description: "燃焼の継続ダメージに対する耐性を貫通する性能。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FROZEN_APPLY_CHANCE", displayName: "凍結付与確率増加", description: "攻撃時に凍結を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "FROZEN_RESISTANCE", displayName: "凍結付与耐性", description: "凍結を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CHILLED_APPLY_CHANCE", displayName: "冷気付与確率増加", description: "攻撃時に冷気を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "CHILLED_RESISTANCE", displayName: "冷気付与耐性", description: "冷気を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_APPLY_CHANCE", displayName: "感電付与確率増加", description: "攻撃時に感電を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_RESISTANCE", displayName: "感電付与耐性", description: "感電を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_INCREASE", displayName: "感電ダメージ増加", description: "感電によって与える継続ダメージを増加させる補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_RESISTANCE", displayName: "感電ダメージ耐性", description: "感電によって受ける継続ダメージを軽減する補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHOCKED_DAMAGE_PENETRATION", displayName: "感電DoT貫通", description: "感電の継続ダメージに対する耐性を貫通する性能。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_APPLY_CHANCE", displayName: "毒状態付与確率増加", description: "攻撃時に毒状態を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_RESISTANCE", displayName: "毒状態付与耐性", description: "毒状態を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_INCREASE", displayName: "毒状態ダメージ増加", description: "毒状態によって与える継続ダメージを増加させる補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_RESISTANCE", displayName: "毒状態ダメージ耐性", description: "毒状態によって受ける継続ダメージを軽減する補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "POISONED_DAMAGE_PENETRATION", displayName: "毒状態DoT貫通", description: "毒状態の継続ダメージに対する耐性を貫通する性能。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BLINDNESS_APPLY_CHANCE", displayName: "盲目付与確率増加", description: "攻撃時に盲目を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "BLINDNESS_RESISTANCE", displayName: "盲目付与耐性", description: "盲目を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "WEAKNESS_APPLY_CHANCE", displayName: "衰弱付与確率増加", description: "攻撃時に衰弱を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "WEAKNESS_RESISTANCE", displayName: "衰弱付与耐性", description: "衰弱を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HEALING_INHIBITION_APPLY_CHANCE", displayName: "回復阻害付与確率増加", description: "攻撃時に回復阻害を付与する確率を高める補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HEALING_INHIBITION_RESISTANCE", displayName: "回復阻害付与耐性", description: "回復阻害を付与されにくくする補正。", category: "CONDITION", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "DEFENSE", displayName: "防御力", description: "物理攻撃から受けるダメージを抑える防御性能。", category: "DEFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MAGIC_DEFENSE", displayName: "魔法防御力", description: "魔法攻撃から受けるダメージを抑える防御性能。", category: "DEFENSE", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "EVASION", displayName: "回避率", description: "攻撃を回避して無効化する確率。", category: "DEFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "KNOCKBACK_RESISTANCE", displayName: "ノックバック耐性", description: "攻撃を受けたときにノックバックしにくくする補正。", category: "DEFENSE", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "HP_REGEN", displayName: "HP回復力", description: "時間経過などでHPを回復する量。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MP_REGEN", displayName: "MP回復力", description: "時間経過などでMPを回復する量。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "ENERGY_REGEN", displayName: "EN回復力", description: "時間経過などでENを回復する量。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MOVEMENT_SPEED", displayName: "移動速度", description: "フィールド上を移動する速さ。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "COOLDOWN_REDUCTION", displayName: "CD短縮", description: "スキルの再使用までに必要な時間を短縮する補正。", category: "UTILITY", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHIELD_RECHARGE_REDUCTION", displayName: "シールドリチャージ短縮", description: "シールドの再充填開始までに必要な時間を短縮する補正。", category: "UTILITY", suffix: "%", decimalPlaces: 1, supportsRange: true },
  { id: "SHIELD_RECHARGE_RATE", displayName: "シールドリチャージ", description: "時間経過などでシールドを再充填する量。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "MINING_SPEED", displayName: "採集速度", description: "採掘や採取などの採集行動を行う速さ。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: true },
  { id: "INVENTORY_SLOTS", displayName: "インベントリスロット", description: "アイテムを保持できるインベントリの枠数。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: false },
  { id: "QUEST_LIMIT", displayName: "クエスト受領上限", description: "同時に受領できるクエスト数の上限。", category: "UTILITY", suffix: "", decimalPlaces: 0, supportsRange: false },
]

export const STATUS_TYPE_BY_ID = new Map<StatusTypeId, StatusTypeDefinition>(
  STATUS_TYPES.map((status) => [status.id, status]),
)

export function isStatusTypeId(value: string): value is StatusTypeId {
  return STATUS_TYPE_BY_ID.has(value as StatusTypeId)
}

export function formatStatusValue(status: StatusTypeDefinition, value: number): string {
  return `${value.toLocaleString('en-US', {
    minimumFractionDigits: status.decimalPlaces,
    maximumFractionDigits: status.decimalPlaces,
  })}${status.suffix}`
}

export function formatStatusModifier(
  status: StatusTypeDefinition,
  modifierType: string,
  value: number,
): string {
  if (modifierType === 'SCALAR') {
    const percentage = value * 100
    const formatted = percentage.toLocaleString('en-US', { maximumFractionDigits: 2 })
    return `${percentage > 0 ? '+' : ''}${formatted}%`
  }
  return `${value > 0 ? '+' : ''}${formatStatusValue(status, value)}`
}
