schemaVersion: 1

database:
  - name: item #カテゴリごとにサブディレクトリが作成されていることを前提とする。
    path: 10.features.item
  - name: enchant
    path: 12.features.enchant
  - name: class
    path: 20.features.class
  - name: skill
    path: 30.features.skill
  - name: mob
    path: 40.features.mob
  - name: mob_spawner
    path: 41.features.mob.spawner
  - name: gathering
    path: 42.features.gathering
  - name: gathering_spawner
    path: 43.features.gathering.spawner
  - name: world
    path: 60.features.world
  - name: dungeon
    path: 65.features.dungeon
  - name: mail
    path: 05.features.mail
  - name: guide
    path: 09.features.guide
  - name: shop
    path: 45.features.shop

  - name: set_effect
    path: 10.features.item/equipment/set_effect

  - name: buff
    path: 70.shared.buff
  - name: loot #サブディレクトリとして、pool, tableが作成されていることを前提とする。
    path: 80.shared.loot
  - name: recipe
    path: 85.shared.recipe

referenceResolver:
  - prefix: "item:"
    database: item
    aliases: ["im"]
  - prefix: "enchant:"
    database: enchant
    aliases: ["en"]
  - prefix: "loot_table:"
    database: loot.table
    aliases: ["lt"]
  - prefix: "loot_pool:"
    database: loot.pool
    aliases: ["lp"]
  - prefix: "buff:"
    database: buff
    aliases: ["bf"]
  - prefix: "class:"
    database: class
    aliases: ["cs"]
  - prefix: "skill:"
    database: skill
    aliases: ["sk"]
  - prefix: "set:"
    database: set_effect
    aliases: ["st"]
  - prefix: "recipe:"
    database: recipe
    aliases: ["rc"]
  - prefix: "shop:"
    database: shop
    aliases: ["sh"]
  - prefix: "mob:"
    database: mob
    aliases: ["mb"]
  - prefix: "mob_spawner:"
    database: mob_spawner
    aliases: ["ms"]
  - prefix: "gathering:"
    database: gathering
    aliases: ["gt"]
  - prefix: "gathering_spawner:"
    database: gathering_spawner
    aliases: ["gs"]
  - prefix: "world:"
    database: world
    aliases: ["wd"]
  - prefix: "dungeon:"
    database: dungeon
    aliases: ["dn"]
  - prefix: "mail:"
    database: mail
    aliases: ["ml"]
  - prefix: "guide:"
    database: guide
    aliases: ["gd"]
